### ISSUE TITLE
Setting sidePanel default width

### ISSUE THREAD

**Issue by normanzhao** [GoogleChrome/chrome-extensions-samples#1011]
With the new Chrome Extension side panel API, is there a way to set the minimum or default width of the side panel? Closing and re-opening, or opening the extension in an incognito browser, resets the resized side panel to the default width.

**Comment by sebastianbenz** [comment]
This is currently not supported. The topic has also been extensively discussed on the [mailing list](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/cJmdMLmpbjg/m/imr8dLY8AQAJ?utm_medium=email&utm_source=footer).

**Comment by lintianleng** [comment]
Is it supported now?

**Comment by oliverdunk** [comment]
This isn't currently supported, but we're continuing to look at it. In particular, there is currently some ongoing work around the sizing for side panels in general (including the built-in ones). Once this work finishes in a few weeks we'd like to revisit what is possible in extensions.

**Comment by Relja92** [comment]
Will there be an update so we can make the sidebar fixed width per our needs perhaps? @sebastianbenz

**Comment by cgilly2fast** [comment]
Has it been decide this feature will not be implemented?  I would very much like it
