### ISSUE TITLE
how to specify the content security policy for content script

### ISSUE THREAD

**Issue by zyucan** [GoogleChrome/chrome-extensions-samples#1062]
In the doc https://developer.chrome.com/docs/extensions/reference/manifest/content-security-policy, there are csp option for `extension_pages` and `sandbox` , but I can't see the option for content script.

**Comment by patrickkettner** [comment]
A content script is a script, so it wouldn't have a CSP. A policy would apply to the entire page. So a content script will be covered by the CSP on the page it is being injected into.
