### ISSUE TITLE
Sample for chrome.types 

### ISSUE THREAD

**Issue by An-Yay** [GoogleChrome/chrome-extensions-samples#1109]
The sample for [chrome.types](https://developer.chrome.com/docs/extensions/reference/api/types) is missing. Kindly assign me for the same!

**Comment by oliverdunk** [comment]
@An-Yay This is actually just a namespace used for some shared types, and doesn't include any APIs, so likely doesn't make sense for a sample. If you have specific ideas feel free to comment here and we can re-open if it makes sense.
