### ISSUE TITLE
A CI to check for grammer mistake in the `.md` files

### ISSUE THREAD

**Issue by ibishal** [GoogleChrome/chrome-extensions-samples#1112]
**Describe the bug**
We need to set up a GitHub Actions workflow to automatically check for grammar mistakes in our Markdown (.md) files. This will help ensure that our documentation and other textual content are clear and error-free.

**Expected behavior**
The CI should check for grammatical errors

**Notes**
Anything additional here. 🌈

**Comment by Min2who** [comment]
Would love to work on this

**Comment by obamwonyi** [comment]
would also love to work on this.

**Comment by jpmedley** [comment]
@oliverdunk I like this idea, but I would like to see what rules this CI tries to enforce. We have to follow the Google style guide. Since style guides can vary, I want to make sure this doesn't just generate a lot of spam that we wouldn't be able follow.

**Comment by jpmedley** [comment]
There's also a potential problem that we would always be asking external contributors to change things that the CI asked to do. This scenario creates more work for all of us.

**Comment by oliverdunk** [comment]
Yeah, following Joe's comment it would be nice if anyone wanting to work on this could propose a specific way they will approach it. For example, the libraries or style rules you intend to use.

**Comment by utnim2** [comment]
> Yeah, following Joe's comment it would be nice if anyone wanting to work on this could propose a specific way they will approach it. For example, the libraries or style rules you intend to use.

I was exploring and was thinking  of using [run check](https://www.npmjs.com/package/write-good)

**Comment by oliverdunk** [comment]
I'm going to go ahead and close this one. I really appreciate the enthusiasm to help, but I don't think this is something we need right now. I worry about the CI being too noisy / unspecific and this doesn't solve a problem we are too worried about today.
