### ISSUE TITLE
I have a problem with the color of the tab page in the console

### ISSUE THREAD

**Issue by zhangkai-dot** [GoogleChrome/chrome-extensions-samples#1135]
I'm not sure where I clicked, resulting in the color of the navigation page like this. I tried to return to the default mode, but it didn't work. I want to go back to the previous color. What should I do? 
<img width="692" alt="15C1BB26-9584-4e20-8F1B-D83BBC6391FD" src="https://github.com/GoogleChrome/chrome-extensions-samples/assets/82517219/19cad3c3-31f5-4f2d-9b71-308f81f16c7c">

**Comment by patrickkettner** [comment]
Hi @zhangkai-dot 
This is apparently the new default color for devtools. You can submit a bug to give feedback on crbug.com, but as this is a repo for chrome extension samples, im going to close this out.
