### ISSUE TITLE
Extension complexity

### ISSUE THREAD

**Issue by eminmammadov** [GoogleChrome/chrome-extensions-samples#1151]
Hello Google Chrome team.

**I suggest you adjust.**

1. **For example, when we pin all the plugins installed in the bar section, they close the connection section, creating confusion due to hierarchical aspects. It may not cause a problem on large screens, but it reduces the user experience on small screens.**

![01](https://github.com/GoogleChrome/chrome-extensions-samples/assets/2352105/ece3448a-4d8d-4b8a-974d-5d2c8caa54c1)

2. **This time when we unpin most of them we suddenly need to go to the All Extensions section to look for the extension we need. Let's say we went and there is no problem with this, but we cannot run that plugin. We need to go and pin that extension first, then go back to our workspace and run it.**

![02](https://github.com/GoogleChrome/chrome-extensions-samples/assets/2352105/65dd0a18-9d52-4343-b362-31e5da229835)
![03](https://github.com/GoogleChrome/chrome-extensions-samples/assets/2352105/540a0801-1688-40f2-85a5-2de2dcbc9e62)

There is no need for this, I think we need to go to tube extensions only for improved features.

**My suggestion is this:**
It would be better to have a search feature in the extensions drop-down menu.

1. **To suddenly find the extension we need, we must "search-pin and run" by opening the extensions menu. This will be a better user experience.**

![04](https://github.com/GoogleChrome/chrome-extensions-samples/assets/2352105/8e312902-f63b-4df2-8b72-688e9d7d1cae)

**Doing this will solve a few problems.**
_1. We don't need to go to the Extensions section to pin.
2. Being able to instantly access the extension we want by staying in our work area.
3. Preventing head confusion._

**Comment by oliverdunk** [comment]
Hi @eminmammadov, thanks for the feedback! I appreciate the time you spent putting together some thoughts and screenshots.

In general, feedback along these lines would be better as a feature request at https://crbug.com/. This repository is specifically for our sample code and other feedback here can't easily be tracked.

I will pass your feedback on, but otherwise closing this out for now.

**Comment by eminmammadov** [comment]
Thank you for your feedback,
