### ISSUE TITLE
Specific SidePanel Site Only Works with Google.com

### ISSUE THREAD

**Issue by jimgilliam** [GoogleChrome/chrome-extensions-samples#1165]
I wanted to use the specific site sidepanel example at https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/functional-samples/cookbook.sidepanel-site-specific. 

If I use any URL besides www.google.com, the extension doesn't work.

Is there something that needs to be on the client side?  For example, if I use www.abcfitness.com in the service worker, update the extension, and go to that site, click the extension action..... nothing happens.

Why?

**Comment by oliverdunk** [comment]
Hi @jimgilliam - have you tried `https://abcfitness.com`? It looks like that site redirects away from the `www` subdomain and the origin needs to be an exact match.

**Comment by oliverdunk** [comment]
Closing for now, feel free to bring any follow-up questions to the mailing list: https://groups.google.com/a/chromium.org/g/chromium-extensions
