### ISSUE TITLE
Error: No window with id: -1

### ISSUE THREAD

**Issue by cicada-ah** [GoogleChrome/chrome-extensions-samples#1172]
chrome.sidePanel.open({tab:id}) api , not working as expected on the pdf page, always throws an error in background.js
![image](https://github.com/GoogleChrome/chrome-extensions-samples/assets/27653885/ec2a40eb-2037-4572-8389-7b2aef41f23a)

**Comment by oliverdunk** [comment]
Hi @cicada-ah, we're tracking this issue here: https://issues.chromium.org/333024278. Feel free to click the +1 button there to receive email updates as it progresses :)
