### ISSUE TITLE
Any ways to change the layout for title bar?

### ISSUE THREAD

**Issue by Xinli-GUMP** [GoogleChrome/chrome-extensions-samples#1217]
As the title, I feel the title bar is so big and occupies so much screen space.
I want the effect like automatically hiding Windows task bar, when cursor moves away from the area of title bar.
Dose any extension can make it?

**Comment by oliverdunk** [comment]
Hi @Xinli-GUMP, could you explain which title bar you are referring to? A screenshot in particular would be very helpful.

**Comment by Xinli-GUMP** [comment]
> Hi @Xinli-GUMP, could you explain which title bar you are referring to? A screenshot in particular would be very helpful.

![recording](https://github.com/user-attachments/assets/00b5e65a-8ad3-4c53-8267-fb09e10443f4)
Just like this screenshot, When cursor moves in the area of tasks bar, it displays and moves out, then  automatically hiding.
Although, I can press F11 to switch the title bar's display in Chrome,  but it will change the layout ouf website,  and I want it automatic.
Thanks for your reply!

**Comment by oliverdunk** [comment]
For this, you'd want to look at the [`requestFullscreen()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen) method. Unfortunately I don't have a specific recommendation for an existing extension to use.
