### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by JAWAD018** [GoogleChrome/chrome-extensions-samples#1235]
Describe the issue : It should have try catch blocks around the code to handle the errors and log error
issue location: C:\Users\mohmm\OneDrive\Desktop\google-chrome\chrome-extensions-samples\api-samples\idle\history.js

it will enhance the quality of code 
Change
![Screenshot 2024-07-20 210426](https://github.com/user-attachments/assets/e3494bfd-f172-4114-b7ee-bc2dd3c72fa5)

**Comment by oliverdunk** [comment]
Hey! I don't believe this would make much of a difference, since the errors should be logged anyway. Going to close this one out based on that.
