### ISSUE TITLE
chrome.usb device not found on Windows

### ISSUE THREAD

**Issue by ohmmmo** [GoogleChrome/chrome-extensions-samples#126]
I have tried to interface sample app with a USB device(Dymo 450 Turbo label printer) on 3 difference machines.
1. Chrome OS : work fine.
2. Mac OS X : app found the device but can't control it. maybe device was under kernel driver. but I'm currently not able to detach it.
3. Windows 7 : asked to give the permission with correct vendor name but "unknown device". when try to transfer data, the console report "device not found"

any suggestion? please help.
Thank you.

**Comment by RimaSGit** [comment]
@kjantzer I was able to detect our printer using the app and also allowed the permission request. But it could not actually print using that printer even after allowing access. Any help?

**Comment by kjantzer** [comment]
@RimaSGit – did you apply this patch: https://github.com/GoogleChrome/chrome-app-samples/commit/9b9fdd6473861d41be4e8a324cf4490d2900c4c3

Other than trying that, I don't have any other advice. I ended up needing to print with the label writer.

**Comment by RimaSGit** [comment]
@kjantzer Thank you Kevin. I have the same patch. The other thing I wanted to make sure is the info endpoint which is “2”, I am not sure how to I get that for my device?
I did use the chrome.usb.listInterfaces to get all that data, there are many endpoints listed in it, so I am not sure which one to use and if I need to convert this to raw address before using it?

Thanks a lot.

**Comment by kjantzer** [comment]
Unfortunately what you said goes right over my head. I have very little experience with hardware and low level programming.

I know that on a mac you can get some device info by opening "System Information"

![screen shot 2015-06-10 at 1 42 18 pm](https://cloud.githubusercontent.com/assets/467487/8093560/acc9e672-0f76-11e5-8390-c7bfa7cb1d5f.png)

**Comment by atvvarna** [comment]
I've set everything but always get in the log:
App was not granted the "usbDevices" permission.
Object {message: "Optional permissions must be listed in extension manifest."}

I didn't see the permission window.
Any help?

**Comment by RimaSGit** [comment]
I think you need this in your manifest.json for usb permissions


"usb_printers":{

   "filters":[

      {

        "vendorId": yourvendorID

      }

     ]

   },

  "permissions": [

    "usb",

   ...........

--

**Comment by reillyeon** [comment]
@atvvarna You need to do with it says, add a "usbDevices" permission dictionary to the "optional_permissions" section of the manifest like this:

```
"optional_permissions": [
    {
      "usbDevices": [
        {
          "vendorId": 3034,
          "productId": 10290
        },
        {
          "vendorId": 3034,
          "productId": 10296
        }
      ]
    }
  ]
```
(copied from the [Radio Receiver](https://github.com/google/radioreceiver/blob/master/extension/manifest.json) app)

**Comment by atvvarna** [comment]
Thanks for the fast reply, yes I have it there but it seems that messed up as tried different IDs.
Now I have:
App was not granted the "usbDevices" permission.
index.js:54 Object {message: "This function must be called during a user gesture"}

**Comment by reillyeon** [comment]
Are you calling the function during a user gesture? Permissions must be requested in the context of an event handler for a user gesture such as clicking a button.

**Comment by atvvarna** [comment]
I didn't modify the code at all, just change the vendor/productIDs.
The printer is found by chrome without any problems and I can print trough standard print dialog of chrome.

**Comment by atvvarna** [comment]
I've just found that in chrome://settings/contentExceptions#plugins if I start the application I see that chrome automatically add block exception. Even if I manually add allow the block is still added on top. What can cause that?
