### ISSUE TITLE
Side Panel does re-show after being closed

### ISSUE THREAD

**Issue by grantdonovan** [GoogleChrome/chrome-extensions-samples#1276]
I am using: functional-samples/cookbook.sidepanel-site-specific

When going to a now allowed site (sidepanel closes) and then going back to an allowed site, the panel does not re-open/show, even though the code executes

1. Go to an allowed site and show panel
2. In the same tab go to a non-allowed site, panel disappears
3. In the me tab go to an allowed site, panel does not re-appear

**Expected behavior**
Panel should always show on allowed sites, even if it was previously closed

**Comment by oliverdunk** [comment]
Hi, this isn't intended behavior but I can see why it might be desirable. The best thing to do would be to open a feature request on https://crbug.com/ and then we can triage accordingly :)
