### ISSUE TITLE
Print labels with Dymo 400

### ISSUE THREAD

**Issue by PNPaul** [GoogleChrome/chrome-extensions-samples#157]
There is a label printer app here that lets you print labels on chrome OS using a dymo 450. I also have a Dymo 400 i would like to use. I tried to modify the code but could not figure it our.
Is there any way to modify the code so i can also use a dymo 400 on chrome OS?

**Comment by ptnwusa** [comment]
Hello Luis Leao.  The company I work for uses Chrome OS for everything and I need to find a way to connect a label printer to our system.  Can you explain your solution to this a little further, please?  Thanks.
