### ISSUE TITLE
usb/knob does not find device

### ISSUE THREAD

**Issue by scheib** [GoogleChrome/chrome-extensions-samples#249]
Run https://github.com/GoogleChrome/chrome-app-samples/tree/master/usb/knob with the Griffin device and it fails to connect.

**Comment by noopole** [comment]
The HID Omnikey 3121 is not recongnized either by Chrome USB although it is detected by Windows.
When I install an alternate driver (WinUDB, libusbK), Chrome can recognize it. 

I opened a case at HID Global, and after  2 weeks investigating, "it appears that it's a problem with the Chrome Platform USB API" (according to HID Device).

Could you work with them to solve this issue?

**Comment by reillyeon** [comment]
"It appears there is a problem" is not very specific feedback to work with. If all you needed to do to resolve the issues was install the WinUSB (or libusbk) driver then this is expected. Chrome cannot access USB devices that don't have one of those drivers loaded and Windows won't load them automatically.

You can accomplish this with a very simple INF file based on Microsoft's [example](https://msdn.microsoft.com/en-us/library/windows/hardware/ff540283(v=vs.85).aspx).

In any case. Please don't hijack this bug as it is referring to a different application and a different piece of hardware than the Omnikey 3121. If there is an issue with the Chrome Apps USB API please open an issue on crbug.com. If driver loading is the only issue, I am sorry, but that is the best we can do on Windows under the limited permissions Chrome runs with.

**Comment by noopole** [comment]
If you think the "feedback" is not "specific" enough then maybe you could contact HID directly to ask for precisions. 

MS workaround is irrelevant in many cases.

Note I hijacked nothing: I've opened a dedicated issue but someone closed it with no solution.

NB: I won't create a Google Code account just to signal an obvious bug! Or sould I do the job for you (Google, nothing personal), and for free?

Sorry for waking this inactive thread up.

**Comment by dengm129** [comment]
#249

**Comment by rios1223** [comment]
Can you guys help me to fix bug

**Comment by rios1223** [comment]
I need help to fix bug some one can help me

**Comment by rios1223** [comment]
I need help with my bug
