### ISSUE TITLE
mDNS-Browser app not able to discover devices on Chrome OS

### ISSUE THREAD

**Issue by jordanaustin** [GoogleChrome/chrome-extensions-samples#251]
When trying to discover devices on Chrome OS using the mDNS browser app you'll get a console log that states "IPv6 address unsupported" which is coming out of the ServiceFinder. There is a todo in the code that simply says "ipv6".

**Comment by gonzojive** [comment]
Consider reopening this issue.  The limitation noted above is no longer an issue, thanks to the resolution of https://code.google.com/p/chromium/issues/detail?id=223004

**Comment by beaufortfrancois** [comment]
Thank you Red!
I've removed the limitation in mdns README file: https://github.com/GoogleChrome/chrome-app-samples/commit/103bd4aed440a6276c36e40bba1c5eedb4c19b69
