### ISSUE TITLE
SyncFileSystem sample app does not work with 'ERROR:requestFileSystem: Sync: service is temporarily unavailable'

### ISSUE THREAD

**Issue by akirattii** [GoogleChrome/chrome-extensions-samples#341]
Im trying 'Sync FileSystem Sample' app on 'Chromium ver.38.0.2125.111 Ubuntu 14.04 (290379) (64-bit)'. 

https://chrome.google.com/webstore/detail/sync-filesystem-sample/ccphiekjjhfnhbmpcbmkmjjhbfhlijkc/support?utm_source=chrome-ntp-launcher

Now I've opened the app and pushed its "Syncable" button, but it does not work with below error message.

ERROR:requestFileSystem: Sync: service is temporarily unavailable. (error code: -105).

Of course, I've tried that on logging-in Chromium with Google account. Why does not it work? Is there something wrong?

Thanks.

**Comment by beaufortfrancois** [comment]
I'm able to reproduce the issue.
Hence I've filed a bug at https://code.google.com/p/chromium/issues/detail?id=455591.

Let's keep this issue opened while the chromium team is investigating.

**Comment by akirattii** [comment]
Hi, beaufortfrancois.
Thank you for filing to BTS.
Incidentally I don't know whether it would be related, but my network handwidth is up to 500kbps...

**Comment by beaufortfrancois** [comment]
Hey @akirattii 
I cannot reproduce the issue with 

```
Google Chrome	42.0.2305.2 (Official Build) dev (64-bit)
Revision	3aa1f92ad47b7402eacda2ade1ede4a42b92d847
Platform	6797.0.0 (Official Build) dev-channel link
```
How about you?

**Comment by akirattii** [comment]
Hey @beaufortfrancois
Sorry for late reply.

Now, I've tried it on Google Chrome Ubuntu 14.04 40.0.2214.115 (64-bit) and then it works well!
But Chromium 40.0.2214.111 (64-bit) is same as usual to occur the error (temporarily unavailable: error code: -105).

Thank you.

**Comment by beaufortfrancois** [comment]
Did you build Chromium by yourself or did your download a build?

**Comment by akirattii** [comment]
I downloaded the build. Not build by myself.

**Comment by beaufortfrancois** [comment]
Where did you download it from?
- https://download-chromium.appspot.com or apt-get?

**Comment by akirattii** [comment]
It is Ubuntu's default installed Chromium. So, I think it is the same origin as apt-get.

**Comment by akirattii** [comment]
Oh, sorry. I've said "I download the build" before, but to be exact, It is Ubuntu's default installed Chromium updated from Ubuntu Software Updates.
So, I think it would be the same origin as apt-get.
At least I have not used https://download-chromium.appspot.com.

**Comment by beaufortfrancois** [comment]
Ok. So now, I am able to reproduce the issue. Here are the steps:

`sudo apt-get install chromium-browser`
Run chromium
Make sure you've signed into chromium with a Google Account
Install https://chrome.google.com/webstore/detail/ccphiekjjhfnhbmpcbmkmjjhbfhlijkc
Go to chrome://syncfs-internals
Run the SyncFileSystem sample
Notice the error `DidInitializeForApp (registered the origin): chrome-extension://ccphiekjjhfnhbmpcbmkmjjhbfhlijkc/: Failed.`

**Comment by beaufortfrancois** [comment]
_Pinging the chromium team at https://code.google.com/p/chromium/issues/detail?id=455591_

**Comment by erayd** [comment]
I can reproduce this on my box. System is Gentoo ~amd64 as at 2015-06-22 11:21am UTC.

Chromium	44.0.2403.30 (Developer Build) (64-bit)
Revision	a45a488c5d27f1a295001ec035c220d3e2129a45
OS	Linux 
Blink	537.36 (@196248)
JavaScript	V8 4.4.63.4
Flash	18.0.0.160
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.30 Safari/537.36
Command Line	chromium-browser --extra-plugin-dir=/usr/lib64/nsbrowser/plugins --ppapi-flash-path=/usr/lib64/chromium-browser/PepperFlash/libpepflashplayer.so --ppapi-flash-version=18.0.0.160 --extra-plugin-dir=/usr/lib64/nsbrowser/plugins --ppapi-flash-path=/usr/lib64/chromium-browser/PepperFlash/libpepflashplayer.so --ppapi-flash-version=18.0.0.160 --flag-switches-begin --enable-app-list --enable-embedded-extension-options --google-profile-info --enable-tcp-fastopen --enable-website-settings-manager --enable-zero-copy --flag-switches-end
Executable Path	No such file or directory
Profile Path	/home/steve/.config/chromium/Default

**Comment by beaufortfrancois** [comment]
For info, what do you see at _chrome://syncfs-internals/_?

**Comment by erayd** [comment]
@beaufortfrancois I see the following (assuming it's the debug log you're after - ifyou want something else, just let me know what):

2015-06-23T01:13:05.049	[VERBOSE] Initializing for App: chrome-extension://ccphiekjjhfnhbmpcbmkmjjhbfhlijkc/
2015-06-23T01:13:05.049	[VERBOSE] [Initialize] Start.
2015-06-23T01:13:05.243	[VERBOSE] [Initialize] Failed to get AboutResource.
2015-06-23T01:13:05.243	[VERBOSE] Service state changed: 1->3: Access forbidden
2015-06-23T01:13:05.243	[VERBOSE] OnRemoteServiceStateChanged: 3 Access forbidden
2015-06-23T01:13:05.243	[VERBOSE] Service state changed: 3->1: Network or temporary service error.
2015-06-23T01:13:05.243	[VERBOSE] OnRemoteServiceStateChanged: 1 Network or temporary service error.
2015-06-23T01:13:05.243	[VERBOSE] DidInitializeForApp (registered the origin): chrome-extension://ccphiekjjhfnhbmpcbmkmjjhbfhlijkc/: Failed.

**Comment by erayd** [comment]
I also tried this again after completely nuking ~/.config/chromium, and signing into chromium with my Google Apps account again. Exactly the same result.

**Comment by beaufortfrancois** [comment]
I'll follow up with chromium team at https://code.google.com/p/chromium/issues/detail?id=455591.
In the mean time, can you reproduce this issue with a brand new Google Account?
Not a Google Apps one.

**Comment by erayd** [comment]
1. Created a brand new Google account, not using Google Apps.
2. Fully quit chromium, then nuked entire ~/.config/chromium directory.
3. Signed into chromium using the new account
4. Installed https://chrome.google.com/webstore/detail/sync-filesystem-sample/ccphiekjjhfnhbmpcbmkmjjhbfhlijkc.
5. Launched the app & attempt to use syncable filesystem; checked chrome://syncfs-internals debug log.

Still failed, with identical results.

**Comment by erayd** [comment]
Have tested on the official (beta) chrome build on Gentoo, and it works perfectly. Looks like it's definitely only chromium which is affected.

Working version of Chrome is below:
```
Google Chrome	44.0.2403.52 (Official Build) beta (64-bit)
Revision	b8d4c934be1120b59ea91c9898c62fde7daf5615-refs/branch-heads/2403@{#320}
OS	Linux 
Blink	537.36 (@197137)
JavaScript	V8 4.4.63.6
Flash	18.0.0.160
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.52 Safari/537.36
Command Line	/opt/google/chrome-beta/google-chrome-beta --user-data-dir=/home/steve/.config/google-chrome-beta --extra-plugin-dir=/usr/lib64/nsbrowser/plugins --extra-plugin-dir=/usr/lib64/nsbrowser/plugins --extra-plugin-dir=/usr/lib64/nsbrowser/plugins --user-data-dir=/home/steve/.config/google-chrome-beta --profile-directory=Default --app-id=fpniocchabmgenibceglhnfeimmdhdfm --flag-switches-begin --flag-switches-end
Executable Path	/opt/google/chrome-beta/google-chrome-beta
Profile Path	/home/steve/.config/google-chrome-beta/Default
Variations	47f591a-3f4a17df
2d23d61d-ca7d8d80
16e0dd70-f23d1dea
6345b824-3d47f4f4
930c120f-ca7d8d80
e950616e-ca7d8d80
e9f4800b-39c30599
19f73432-ca7d8d80
76b48ab8-a2567007
31362330-ca7d8d80
c70841c8-4866ef6e
9d315c2-ca7d8d80
a3e00cc3-3d47f4f4
b2638b4d-3f4a17df
1d3ad72e-3f4a17df
9e5c75f1-8f74492d
f79cb77b-3f4a17df
3a716e87-3d47f4f4
97dfc274-3f4a17df
ca65a9fe-91ac3782
4ea303a6-3f4a17df
fa99bb73-3f4a17df
61544484-a24f2f50
313d831b-e49daded
9736de91-ca7d8d80
b2612322-f8cf70e2
c99b9cf4-3f4a17df
be53c1f1-27454201
244ca1ac-4ad60575
3ac60855-486e2a9c
f296190c-19dcaa1a
4442aae2-7158671e
ed1d377-e1cc0f14
75f0f0a0-a5822863
e2b18481-92bb99a9
e7e71889-e1cc0f14
b39ea213-3d47f4f4
cbf0c14e-bf3e6cfd
```

**Comment by beaufortfrancois** [comment]
I'm not 100% sure but I wonder if that issue happens because Chromium API Keys are not allowed to access the Drive API. See https://www.chromium.org/developers/how-tos/api-keys for more background.

Maybe @floppym could have a look at the Google Developers Console and confirm or not that the Drive API is enabled. See below.
![screenshot 2015-06-29 at 3 28 45 pm](https://cloud.githubusercontent.com/assets/634478/8408828/8e935c54-1e73-11e5-8742-94c22318d5c0.png)

**Comment by Eldelshell** [comment]
I'm having the same results here, using the example or even one of my own apps in Chromium:

Version 44.0.2403.89 Ubuntu 14.04 (64-bit)

```
2015-09-11T09:46:01.199	[VERBOSE] Initializing for App: chrome-extension://ccphiekjjhfnhbmpcbmkmjjhbfhlijkc/
2015-09-11T09:46:01.199	[VERBOSE] [Initialize] Start.
2015-09-11T09:46:01.282	[VERBOSE] [Initialize] Failed to get AboutResource.
2015-09-11T09:46:01.282	[VERBOSE] Service state changed: 1->3: Access forbidden
2015-09-11T09:46:01.282	[VERBOSE] OnRemoteServiceStateChanged: 3 Access forbidden
2015-09-11T09:46:01.282	[VERBOSE] Service state changed: 3->1: Network or temporary service error.
2015-09-11T09:46:01.282	[VERBOSE] OnRemoteServiceStateChanged: 1 Network or temporary service error.
2015-09-11T09:46:01.282	[VERBOSE] DidInitializeForApp (registered the origin): chrome-extension://ccphiekjjhfnhbmpcbmkmjjhbfhlijkc/: Failed.
```

From another app I get the same result, so this is probably not an issue with the demo but with Chromium.

**Comment by Eldelshell** [comment]
Tried the same flows (demo and my app) and both work fine in Chrome stable for Debian Version 45.0.2454.85 (64-bit)

So yes, this is a problem with Chromium, not the app itself.

**Comment by beaufortfrancois** [comment]
As stated in https://github.com/GoogleChrome/chrome-app-samples/issues/341#issuecomment-116660229, you may want to ask Chromium package maintainer to update its API keys.
See https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=chromium
