### ISSUE TITLE
Convert mdns-browser sample to use chrome.mdns API

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/chrome-extensions-samples#387]
Since `chrome.mdns` is now available to everyone, let's convert our sample to use it.
See https://codereview.chromium.org/668983003

**Comment by lostsource** [comment]
Gave this a shot on Canary however I seem to be passing an incorrect `serviceType` (maybe) .. This code returns an empty array

    chrome.mdns.onServiceList.addListener(
       function(e) {
        console.dir(e); 
       },
       {
          serviceType:'_smb'
       }
    );

While the current app implementation (without `chrome.mdns`) does show an entry for `_smb`

![mDNS Browser](http://i.imgur.com/AeL1POj.png)

Ideas ?

**Comment by beaufortfrancois** [comment]
I'm not a MDNS expert but it looks like serviceType should be `_smb._tcp` according to https://github.com/GoogleChrome/chrome-app-samples/blob/0e4bceda90f56ccae91e98db2c1b191daffb41a0/samples/mdns-browser/service-types.js#L60

Do you mind trying again and let me know?

**Comment by beaufortfrancois** [comment]
OK I think I know what is happening there... Try with `_smb._tcp.local` instead or `_smb.local`. 
From what I understand, `.local` always needs to be appended to filter.

**Comment by lostsource** [comment]
yep that works! will try to find some time to work on this

**Comment by briansturgill** [comment]
Where is chrome.mdns documented? Is this still in canary?

**Comment by beaufortfrancois** [comment]
It's now in stable: https://developer.chrome.com/apps/mdns
I've created recently an App that uses https://plus.google.com/u/0/+FrancoisBeaufort/posts/9wKfokmgbnj.

I'll update this sample to use it soon.

**Comment by briansturgill** [comment]
Thanks... how did you know it was there?
Why isn't on the main page: https://developer.chrome.com/apps/api_index?
It's great as far as it goes... why can't we publish a service as well?
The whole point of mdns is for peers to be able to find each other without heavy infrastructure, half such an API is almost as bad as no API at all.
I'm getting pretty disgusted with Chrome Apps... the exact same problem exists in the Bluetooth LE api... only half there.

**Comment by beaufortfrancois** [comment]
I've just filed a bug regarding this particular feature at http://crbug.com/498140 you can star to get updates from the Chromium Team.

 Regarding https://developer.chrome.com/apps/api_index not showing the chrome.mdns API, I will investigate and let you know when it's fixed. It's definitely a bug.

**Comment by briansturgill** [comment]
I just filed a feature request: https://code.google.com/p/chromium/issues/detail?id=498395
asking for the publish side of chrome.mdns.
It upsets me that I have to ask for that. The bulk of the Chrome API for Chrome Apps has this sort of obvious missing functionality. My patience with Chrome Apps is wearing thin. Is there a roadmap available for Chrome Apps? With Google now seeming to push Android apps for ChromeOS, with all the problems developers are facing in the Chrome Web Store and little in the way of development of the Chrome APIs (I mean most of the new ones are ChromeOS only). Well, alternatives like Atom Shell and WinRT/JS are looking much more interesting. I'd really like to support Chrome devices, but too many things are missing.

**Comment by beaufortfrancois** [comment]
Thanks for filing this feature request. I've cced some people who might be interested.
