### ISSUE TITLE
bluetooth-samples/device-info-demo fails with error

### ISSUE THREAD

**Issue by tomisaacson** [GoogleChrome/chrome-extensions-samples#398]
The sample bluetooth-samples/device-info-demo fails with the error "Uncaught TypeError: Cannot read property 'getAdapterState' of undefined".

**Comment by beaufortfrancois** [comment]
As noted in https://developer.chrome.com/apps/bluetooth, _This API works only on OS X, Windows and Chrome OS._ Which platform are you running on?

**Comment by tomisaacson** [comment]
I've tried it on Windows and OS X, same problem.

**Comment by beaufortfrancois** [comment]
It looks like the error says `chrome.bluetooth` is `undefined`.
It should not be the case when `bluetooth` is in your manifest.

Did you update manifest somehow?

**Comment by tomisaacson** [comment]
No. I'm using a standard install of Chrome 43 and opening main.html from Github, I haven't changed anything.

Are you saying that this works for you?

**Comment by beaufortfrancois** [comment]
As stated in https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/bluetooth-samples/device-info-demo, you might want to install the Chrome App from https://chrome.google.com/webstore/detail/device-information-servic/dblimghcclaakknbpajckcamddhjaaai  and try again. It should work better that way.

**Comment by KirthikaRajesh** [comment]
The sample bluetooth-samples/device-info-demo fails to discover the nearby devices. Can anyone help me with this issue..?
