### ISSUE TITLE
Made changes, still no luck running as Localhost

### ISSUE THREAD

**Issue by danjpalmer** [GoogleChrome/chrome-extensions-samples#409]
Hi Francois,

I updated the index.js with the three lines and this did increase the timeout but still came back as connection lost.
The dev console showed:

WebSocket connection to 'ws://localhost:5103/WebSocketServer/' failed: Error during WebSocket handshake: Unexpected response code: 200

Happy to do any testing you need my end. Again, this is for example https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/websocket-server

**Comment by beaufortfrancois** [comment]
Port used in `websocket-server` is 9999 not 5103 as I can read your error message.
Can you run successfully https://chrome.google.com/webstore/detail/websocket-server-test/pkbpddppnkjmlbgliipgmhjeialadokj?

**Comment by danjpalmer** [comment]
When posted to the app store it works great! 

We're building something that uses sockets and using your project as a baseline. The issue is we want to make changes to the code and test WITHOUT having to post it to the Chrome App Store. It's just not efficient to do so. 

How do I run your example successfully without using the Chrome App Store?

Thanks

**Comment by beaufortfrancois** [comment]
You can simply clone the chrome-app-samples repository with `git clone https://github.com/GoogleChrome/chrome-app-samples` then open Chrome, go to `chrome://extensions`, check "Developer mode" checkbox, click on "Load unpacked extension", and select the `samples/websocket-server` in the `chrome-app-samples` Git repository.

**Comment by danjpalmer** [comment]
Perfect. Thank you for your time and help

**Comment by davewallace** [comment]
This is amazing, I'm about to use your telnet stuff and the advice in this thread to now create a chrome extension for a 25 year old internet game available in the browser. I'm not the first to do it, obviously you've done it with Aardwolf (where I've had a lurk character there - Anfauglir - since before the last breaking, around 2002), now I'll have a go at doing it for Astaria too (astaria.net:5000).
