### ISSUE TITLE
error message when svg fails to load from relative file url path is confusing

### ISSUE THREAD

**Issue by eedeebee** [GoogleChrome/chrome-extensions-samples#410]
Unsafe attempt to load URL file:///Users/ericbloch/repos/set/shapes.svg#oval from frame with URL file:///Users/ericbloch/repos/set/index.html. Domains, protocols and ports must match.

The domain, protocol and port all match as I"m merely trying to load an svg file into the index.html file.  I'm guessing there is some security issue... and if not, then this is simply a bug instead.

here is an example html file to test:

```
<!DOCTYPE html>
<html>
  <body>
      <svg>
          <use xlink:href="shapes.svg#oval"/>
      </svg>
  </body>
</html>
```

And a a svg file:

```
<svg xmlns="http://www.w3.org/2000/svg" version="1.1"> 
<g id="oval">
    <circle cx="90" cy="30" r="18" />
    <circle cx="90" cy="70" r="18" />
    <rect x="72" y="30" width="36" height="36" />
</g>
```

**Comment by beaufortfrancois** [comment]
I'm not sure to understand how this relates to Chrome Apps there.
