### ISSUE TITLE
how to break through Windows' firewall?

### ISSUE THREAD

**Issue by zhaojun12** [GoogleChrome/chrome-extensions-samples#411]
- I use tcpServer API to create a tcp server in Windows 7 system listening on port 9003
- But others cannot connect to it because the windows firewall forbids inbound traffic with port 9003
- I wonder if there is an API allowing the chrome app to write a firewall rule to allow inbound traffic with specific port number?
- Of course when chrome app wants to write a firewall rule, it needs User's permission, in case of User has no idea about how to configure firewall rule.

Thanks.

**Comment by fiatjaf** [comment]
I think this issue has no solution, but it enlightened me about the issue of Windows Firewall, which I had completely forgotten about and was causing me a lot of uneasiness.
