### ISSUE TITLE
Port doesn't seem to disconnect properly when app closes

### ISSUE THREAD

**Issue by nightswimmer** [GoogleChrome/chrome-extensions-samples#420]
The application works fine for me when I run it the first time. I can connect several clients to the server without any issue. But when I close the server and open it again, it doesn't work anymore. The port is not available, I get this error in the console:

Unchecked runtime.lastError while running socket.listen: Could not listen on the specified port.
    at Object.callback (chrome-extension://caaahhaifmadednjncngiplcbafblklm/http.js:257:14)reportIfUnchecked @ extensions::lastError:133
extensions::uncaught_exception_handler:8 Error in response to socket.accept: Error: Invocation of form socket.read(undefined, function) doesn't match definition socket.read(integer socketId, optional integer bufferSize, function callback)

I need to kill all chrome processes in task manager to make it work again.

**Comment by beaufortfrancois** [comment]
Which app are you running?

**Comment by nightswimmer** [comment]
Oooops sorry forgot to say... It's the websocket-server.

**Comment by nightswimmer** [comment]
Also forgot to say... The previous behaviour I described happens in Windows 10. On a Mac computer (OS 10.10.1) the app also runs normally the first time, but when we close it and open again it crashes all chrome windows.

**Comment by reillyeon** [comment]
Can you open chrome://crashes, find the crash report corresponding to the time when you encountered the issue and file a bug?

**Comment by nightswimmer** [comment]
Ok... Is this what you need?
report_id:2e63469424036cfa

**Comment by reillyeon** [comment]
Yes, thank you. I'm taking a look.
