### ISSUE TITLE
Chrome app Identity

### ISSUE THREAD

**Issue by onigetoc** [GoogleChrome/chrome-extensions-samples#426]
After testing Chrome app Identity, there's a illogical step to do to get user informations.

If i'm already connected to Oauth i just have to click the button get user info and it's okay.
But if i'm not signed in, we should click twice on the signing button and once on the getuser infos to see the user infos, it's a lot of clicks to get user infos.

**Comment by beaufortfrancois** [comment]
I'm not sure to understand what is wrong there.
Clicking "get personal data" could be done automatically when user clicks on the "sign in" button. Is that it?

**Comment by onigetoc** [comment]
Yes, probably, but based on the identity exemple, i didn't really figured out how to show user infos automatically after i get the Token. Instead of clicking another time on the getuser infos button.

Because i don't know when the token is successfully received and then show user infos without another click

**Comment by beaufortfrancois** [comment]
According to https://github.com/GoogleChrome/chrome-app-samples/blob/ba78d3b1574631152b4b22f5b44ae748738fff97/samples/identity/identity.js#L209, it looks like you simply need to call `getUserInfo(false)` after https://github.com/GoogleChrome/chrome-app-samples/blob/ba78d3b1574631152b4b22f5b44ae748738fff97/samples/identity/identity.js#L39
