### ISSUE TITLE
Login in g+ using identity 

### ISSUE THREAD

**Issue by jitsingh89** [GoogleChrome/chrome-extensions-samples#432]
not able to fill email id and password using identity. I have to login in g+ using identity where i should pass email id and password in google api, then I want to access the detail of users.I want pass credential in same windows, I don't want to redirect to chrome browser.

**Comment by beaufortfrancois** [comment]
I'm not sure to understand the issue there.
Can you provide specific steps to what you're trying to accomplish?

In the mean time, check out https://developer.chrome.com/apps/identity

**Comment by jitsingh89** [comment]
using identity only same user is able to login. but I have login with different user credential on different machine. one more thing, whenever 1) I am adding crx flie the i am not able to open pur user details.
2) Which key I have to put in manifest file. How to create the key is it free or paid to generate key.
