### ISSUE TITLE
<webview> Browser: Cannot load new page after crashed view

### ISSUE THREAD

**Issue by avallee** [GoogleChrome/chrome-extensions-samples#433]
If i hit the simulate crash button, I'll see "Aw, Snap!" page. However, once I hit reload it changes to a sad mac/sad tab icon on a black page and the browser is dead until i close and reopen it.

**Comment by beaufortfrancois** [comment]
I can't reproduce this issue.
Which OS do you use?
Which chrome version do you use (see about:version)?

**Comment by avallee** [comment]
I'm getting the problem on ToT Chromium. I think this might be a webview bug, not the sample.

```
Chromium		51.0.2696.0 (Developer Build) (64-bit)
Revision		efb0407ede1da3162449ba51c7743a5b5a477589-refs/heads/master@{#384286}
OS				Linux 
Blink	537.36	(@efb0407ede1da3162449ba51c7743a5b5a477589)
```
