### ISSUE TITLE
Why does "One Time Payment Sample" app from CWS keep taking the user to the chrome sign in page?

### ISSUE THREAD

**Issue by MGTHEBOSS** [GoogleChrome/chrome-extensions-samples#439]
I have installed the ["One Time Payment Sample" app from CWS](https://chrome.google.com/webstore/detail/one-time-payment-sample/ebcgmmcbgnpoclkoibogeiokfdmjbbob) to observe the flow of the app. When I click on the app, it opens the app window (see the attached image), which shows "Loading license data..." and it also opens the "Sign in to Chrome" page in a new tab, when I sign in nothing happens, license data does not get loaded. I would like to know why this is happening and what the solution is.

![one time payment sample loading](https://cloud.githubusercontent.com/assets/3612991/14847316/9aced5e2-0c85-11e6-9e54-8f80c16c3093.png)

**Comment by beaufortfrancois** [comment]
It works flawlessly for me ;(
I got the app window, then the "Sign in to Chrome" window, signed in, and got back the auth token as you can see.

![screenshot 2016-04-27 at 8 33 20 am](https://cloud.githubusercontent.com/assets/634478/14843695/b7f918ea-0c52-11e6-8110-2dc699eb08c6.png)

Can you open a tab to `chrome://inspect/#apps`, click on the Inspect link on the One Time Payment Sample and share what you're seeing there. Here's how it looks for me:
![screenshot 2016-04-27 at 8 35 53 am](https://cloud.githubusercontent.com/assets/634478/14843754/12746a68-0c53-11e6-84d7-7e4a8ec96c80.png)

**Comment by MGTHEBOSS** [comment]
I was using an account which was opened in the United States from India. This time, I used an account which was opened in India and at least got a response (see the attached image), I have attached your requested image also.

![one time payment sample none](https://cloud.githubusercontent.com/assets/3612991/14844040/3940a570-0c72-11e6-894e-d32a04605a1c.png)

![inspect](https://cloud.githubusercontent.com/assets/3612991/14844048/4727838e-0c72-11e6-85a7-290868ee064b.png)

**Comment by MGTHEBOSS** [comment]
I have two questions, the first one is, why I am not getting the same license data as you, and second, why it was not working with the account which was opened from the US.

**Comment by beaufortfrancois** [comment]
Could that be because of https://developer.chrome.com/webstore/pricing#seller?
@petele may help us there.

**Comment by MGTHEBOSS** [comment]
Interesting.
