### ISSUE TITLE
sample managed-in-app-payments is not working

### ISSUE THREAD

**Issue by lsn793** [GoogleChrome/chrome-extensions-samples#450]
Just run managed-in-app-payments and google.payments.inapp.getSkuDetails returns error INVALID_RESPONSE_ERROR

**Comment by tranzium** [comment]
Just incorporated the buy.js file into my extension and receiving the same error message.

**Comment by drveresh** [comment]
It's local copy is working for me, but how it is able to pull its virtual items locally, but same failing for our local extensions trying to get our items?
