### ISSUE TITLE
Chrome Samples

### ISSUE THREAD

**Issue by pavneet11** [GoogleChrome/chrome-extensions-samples#463]
I Downloaded The Code Provided Here In Github Regarding Chrome Samples.and ran the same in chrome browser on my computer.
but no sample is working.

Do i need to install any extra plugin? or do i need any modifications in the JSON file.

I tried all of the samples . none of them were working.

i need to run chrome desktop capture first as i am making a project on this

when i click enable capture nothing happens.

**Comment by beaufortfrancois** [comment]
What is your platform?
How do you launch a chrome app?
