### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getAuthToken' of undefined?

### ISSUE THREAD

**Issue by MahendraPrasad** [GoogleChrome/chrome-extensions-samples#484]
```
chrome.identity.getAuthToken({ 'interactive': true },
			function(token) {
				if (chrome.runtime.lastError) {
					alert(JSON.stringify(chrome.runtime.lastError));
					} else {
						alert(token);
					}
		});
```

Here, i am getting the error in first line.

and this the manifest of permission:
`"permissions": ["identity", "https://www.googleapis.com/",  "https://accounts.google.com/", "https://*.googleusercontent.com/","https://*.chromiumapp.org/*", "https://accounts.google.com/o/oauth2/v2/auth"],`

**Comment by ZachSaucier** [comment]
It may require providing a "key" value in your manifest as well. You can either use the same key as the one you get when you upload your extension to the webstore or try [packing an extension](https://stackoverflow.com/a/44799636/2065702) to generate a new one (though I couldn't get this second approach working myself).

**Comment by rashikcs** [comment]
Has it been resolved?? I am kind of facing the same problem and I put the key field getting the value from generated .pem file and added client_id from google console but still the problem persist.

![Screenshot from 2019-10-14 11-09-20](https://user-images.githubusercontent.com/18161407/66740322-26bbc380-ee73-11e9-8364-3a37b4eed17b.png)
![Screenshot from 2019-10-14 11-09-35](https://user-images.githubusercontent.com/18161407/66740323-27545a00-ee73-11e9-831e-1ff929564e20.png)

**Comment by jliukai** [comment]
im also facing the exact same issue as @rashikcs . used the key value in the generated pem file. but i still get this error. any help?

**Comment by zdravko61** [comment]
@jliukai 

you have to do it from a background script otherwise it will not work and it will give you chrome identity as undefined.

https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/identity

here in the example in the manifest you have background script defined as main.js this script uses index.html to load the identity script and so it's working as a backround script.  Just check the background scripts docs and how to exchange events between content and background and you will be good.

**Comment by Seamus1989** [comment]
> It may require providing a "key" value in your manifest as well. You can either use the same key as the one you get when you upload your extension to the webstore or try [packing an extension](https://stackoverflow.com/a/44799636/2065702) to generate a new one (though I couldn't get this second approach working myself).

it may?
