### ISSUE TITLE
How to develop a chrome app for gmail attachments->open with->connect more apps?

### ISSUE THREAD

**Issue by MahendraPrasad** [GoogleChrome/chrome-extensions-samples#485]
I am new to chrome apps, i don't know how to develop chrome apps.
i have a pdf in gmail attachments, if i click the pdf will open with popup screen and in there open with is there in top? if i click on open with, connect more app will appear, so like that if i search any apps it will take me to web store, like how to develop and publish my own app?

I tried but im not gtiing till now,... Please help me?

emailid: mahendraveeregowda@gmail.com

**Comment by htatkyaww** [comment]
+1
