### ISSUE TITLE
[samples/camera-capture] Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided (app.js:46)

### ISSUE THREAD

**Issue by shainakrumme** [GoogleChrome/chrome-extensions-samples#497]
**File**: [GoogleChrome/chrome-app-samples/samples/camera-capture/app.js](https://github.com/GoogleChrome/chrome-app-samples/blob/master/samples/camera-capture/app.js)

**Error Message**: Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided ([app.js:46](https://github.com/GoogleChrome/chrome-app-samples/blob/master/samples/camera-capture/app.js))

**Comment by clarodanesh** [comment]
the example should be updated to include the `video.srcObject` per the MDN docs.
[](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL)
