### ISSUE TITLE
Organizing Manifest V3 extensions samples 

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/chrome-extensions-samples#526]
I'd like to start adding samples of Manifest V3 extensions this repo and I'm curios if anyone has strong feels on how we should organize them. At the moment I'm thinking of either doing one of the below options.

## Option 1

```
├── api/
├── apps/
├── extensions/
│   ├── mv2/
│   │   └──<existing extensions samples>
│   └── mv3/
│       └── <put new samples here>
├── howto/
├── tools/
├── tutorials/
└── …
```

In this proposal we would create two new subdirectories in the extensions directory: `extensions/mv2/` and `extensions/mv3/`. All existing samples would be moved into `mv2/` and new MV3-specific samples would be placed in the `mv3/` subdirectory.

## Option 2

```
├── api/
├── apps/
├── extensions-mv2/
│   └── <existing extensions samples>
├── extensions-mv3/
│   └── <put new samples here>
├── howto/
├── tools/
├── tutorials/
└── …
```

Rename `extensions/` to `extensions-mv2` and leave existing extensions samples in this directory. Create a new directory named `extensions-mv3` to house all new extensions examples.

## After MV2 is sunset

Once MV2 is retired, we can either move back to a single `extensions/` directory or we can leave the MV3 naming as is in anticipation of an eventual MV4 set of samples.

**Comment by jfunction** [comment]
One pro of option 2 is that relative directories retain their meaning but it shouldn't make a difference right? In both cases the MV2 samples will be in a folder they were not in previously. 

I'm **very** keen to see some MV3 samples as the internet doesn't seem to have much on this and the docs are still using background scripts. 

eg https://developer.chrome.com/docs/extensions/mv3/getstarted/

**Comment by JWess** [comment]
I am also here wishing there were at least one good V3 sample extension. I think I prefer option 2 of those suggested above.

**Comment by dotproto** [comment]
I didn't originally understand the organization of this repo and assumed that only the "extensions" directory needed to be updated: `api`, `extensions`, `howto`, and `tutorials` all contained MV2 code. As such, I ended up creating the [mv2-archive](https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/mv2-archive) directory and moving the those 4 folders into them. As I add port MV2 samples or create new ones, I'll recreate the appropriate top level directories.
