### ISSUE TITLE
Chrome extension client side showing successful but server generating 500 error

### ISSUE THREAD

**Issue by DaniyalDhz** [GoogleChrome/chrome-extensions-samples#535]
I am trying to make a POST call from chrome extension/client-side to flask server.

background.js

```
fetch('http://0.0.0.0:5000/test',
    {
        method:'POST',
            body: JSON.stringify({"name":"daniel"}),
        headers: {
          "Content-Type": "application/json;charset=UTF-8",
          'Accept': 'application/json'
        }       
    })
    .then(response => response.json())
  .then(json => console.log(JSON.stringify(json))); 
```
manifest.json

```
{
    "manifest_version": 2,
    "name": "To be named",
    "description": "This extension helps...",
    "version": "0.1.0",
    "permissions": [
        "identity",
        "identity.email",
        "http://0.0.0.0:5000/test"
    ],
    "background": {
        "scripts": ["background.js"],
        "persistent": false
    },  
    "content_scripts": [{
        "matches": ["https://www.youtube.com/"], 
        "js": ["content.js"],
        "css": ["styles.css"]
    }]
}
```
PY (flask)

```
@blueprint.route('/test', methods=['GET', 'POST'])
def test():
    if request.method == 'POST':
        return request.json#{"status": "OK", "status_code": 200, "data": data}
    elif request.method == 'GET':
        return request.json
    else:
        return 'nothing printed'
```
Solutions tried so far:

request.loads/dumpts(request.json)

Installing CORS on flask

changing Content-Type to Content-'t'ype

^All these solution just returned null as a response instead of error and didn't get the actual data as presented in the background console

Background js console

<img width="892" alt="Screen Shot 2020-12-27 at 10 30 09 PM" src="https://user-images.githubusercontent.com/58639693/103194962-3cb67800-48af-11eb-8a15-432efdcaa69f.png">

yet getting:
<img width="1175" alt="Screen Shot 2020-12-28 at 1 43 57 AM" src="https://user-images.githubusercontent.com/58639693/103195007-5952b000-48af-11eb-9f35-4beaf9a6d2e5.png">

`TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
`
The reason I think it's related to chrome extension being at default is because when I test the same code in any other js file i get the data from server side (flask) and not null.

**Comment by jfunction** [comment]
You are getting a Flask error there. We need to dig a little deeper to see if it's an extension error. Can you set a breakpoint inside your flask apps `test` function and inspect the incoming request object to see if it of the expected type and has expected content?

**Comment by DaniyalDhz** [comment]
@jfunction Thanks for getting back. I don't see anything coming back as it's None. The type and content is shown in the screenshot posted yet the data can't be posted in a flask app. It'd be best if you could try it on your end & see if it work for you cause [SO](https://stackoverflow.com/questions/65472735/chrome-extension-client-side-showing-successful-but-server-generating-500-error/65472845?noredirect=1#comment115754257_65472845), senior developers, and I have tried every way possible to get it to work & couldn't.

**Comment by DaniyalDhz** [comment]
I aslo get `Uncaught (in promise) SyntaxError: Unexpected token d in JSON at position 0`
when doing:
```
fetch('http://0.0.0.0:5000/test',
    {
        method:'POST',
            body: JSON.stringify({"name":"daniel"}),
        headers: {
          "Content-Type": "application/json;charset=UTF-8",
          'Accept': 'application/json'
        }       
    })
    .then(response => response.json())
  .then(json => console.log(JSON.stringify(json))); 

```

```
@blueprint.route('/test', methods=['GET', 'POST'])
def test():
    data = request.json
    return "data is " + format(data)

```

**Comment by DaniyalDhz** [comment]
@jfunction thanks for getting back! Everything is working well.
