### ISSUE TITLE
chrome.webRequest.onAuthRequired is not fired first time when using Fetch API

### ISSUE THREAD

**Issue by skaeff** [GoogleChrome/chrome-extensions-samples#540]
Hi,

While developing some Selenium tests with Chrome Driver for some in-house web site, i faced with HTTP corporate proxy with authentication, because some JS scripts on in-house web-site page use Fetch API to query some public domains over Internet.

So this (https://stackoverflow.com/a/55582859) answer was very usefull, but i found strange bug:
chrome.webRequest.onAuthRequired is not fired when only Fetch API is used to go over proxy!
Workaround: you should query some public Internet site first, then Fetch API proxy works.

**Comment by dotproto** [comment]
This issue appears to describe a Chrome bug rather than a bug report or feature request for the chrome-extensions-samples repository. Please visit https://crbug.com/new to file a bug report.
