### ISSUE TITLE
DOMParser is not defined when use the function suggest in chrome.omnibox.onInputChanged.addListener

### ISSUE THREAD

**Issue by normanfan** [GoogleChrome/chrome-extensions-samples#541]
chrome version  90.0.4393.0   canary (x86_64)
when i set the `manifest_version` to 3, something wrong happend
// code
chrome.omnibox.onInputChanged.addListener(
  function(text, suggest) {
    console.log('inputChanged: ' + text);
    suggest([
      {content: text + " one", description: "the first one"},
      {content: text + " number two", description: "the second entry"}
    ]);
  });

// error
extensions::omnibox:24 Uncaught ReferenceError: DOMParser is not defined
    at parseOmniboxDescription (extensions::omnibox:24)
    at extensions::omnibox:101
    at Object.suggestCallback [as suggest] (extensions::omnibox:116)
    at eval (eval at <anonymous> (background.js:9), <anonymous>:1:1)
    at background.js:9
    at extensions::omnibox:118

**Comment by raul4rmas** [comment]
I got the same error

**Comment by alxbrn** [comment]
I'm experiencing the same behavior.

**Comment by dotproto** [comment]
Unfortunately this appears to be a platform bug, not an issue with the example repository. I've opened https://crbug.com/1186804 in response to this issue.

**Comment by liyunfei22** [comment]
I got the same error
