### ISSUE TITLE
Links don't work

### ISSUE THREAD

**Issue by rvong** [GoogleChrome/chrome-extensions-samples#547]
From the main page "My Bookmarks" takes you to a 404 page.

**Comment by DanielOberlechner** [comment]
Same thing with this Demo:
WebNavigation Tech Demo

Also doesn't work. Maybe if you have a chance to fix this?!

Greets Daniel :)

**Comment by mkrl** [comment]
It seems like it is related to this PR https://github.com/GoogleChrome/chrome-extensions-samples/pull/542 that moved all MV2 recources into a `mv2-archive` directory. Looking at @dotproto's comment there, it looks like it's already being worked on :)

**Comment by dotproto** [comment]
Looks like both the "My Bookmarks" and "WebNavigation Tech Demo" links are working as expected in the [mv2-archive directory's README](https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/mv2-archive).
