### ISSUE TITLE
Webrequest not working in Manifest_version 3 .

### ISSUE THREAD

**Issue by Abrahamw007** [GoogleChrome/chrome-extensions-samples#564]
Webrequest not working in Manifest_version 3 .
webRequestBlocking' requires manifest version of 2 or lower.
Nothing to see here, move along

**Comment by dotproto** [comment]
This issue does not appear to contain a bug report. See https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#when-use-blocking-webrequest
