### ISSUE TITLE
Update omnibox sample to v3 manifest

### ISSUE THREAD

**Issue by skyhirider** [GoogleChrome/chrome-extensions-samples#575]
Could you update the omnibox examples for the new manifest?

https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/mv2-archive/api/omnibox

Thanks!

**Comment by kevinwhoffman** [comment]
When using manifest v3, I'm not able to add auto suggestions to the omnibox when input is changed. I tried using the following snippet from the v2 example, but it doesn't work. 

https://github.com/GoogleChrome/chrome-extensions-samples/blob/e716678b67fd30a5876a552b9665e9f847d6d84b/mv2-archive/api/omnibox/simple-example/background.js#L9-L16

When I add the snippet to `background.js` and then reload the extension, I get the following error:

![image](https://user-images.githubusercontent.com/1938671/114130120-e73a3000-98cd-11eb-91c6-12c645e1be99.png)

An updated example that demonstrates suggestions would be greatly appreciated.

**Comment by kevinwhoffman** [comment]
For anyone who is encountering errors with the omnibox API using manifest v3, note there is an open bug with the platform that prevents the omnibox from displaying suggestions. More details provided in https://github.com/GoogleChrome/chrome-extensions-samples/issues/541#issuecomment-796206471.

In the meantime, the only way I can get the omnibox to display suggested results is to use manifest v2.

**Comment by itxve** [comment]
I have a question，in v3 manifest , the background.js Can only be in the same directory as manifest.json 🤔️?
"background": {
    "service_worker": "background.js"
  },

**Comment by skyhirider** [comment]
I've read that the issue with the manifest was fixed, if it is so could you now prepare a working v3 sample for using this feature?

**Comment by patrickkettner** [comment]
this was fixed in #573
