### ISSUE TITLE
Chrome Extension - Service Workers not activating on event 

### ISSUE THREAD

**Issue by casendler** [GoogleChrome/chrome-extensions-samples#587]
**Describe the bug**
I recently build an extension with a pop-up on mv3 and I'm facing a bug related to service worker event listeners. The extension works properly for an initial period, however after an undefined period of inactivity the service workers go inactive (this is expected per the documentation). The issue however, is that the service worker is not reactivated on a new triggering event. We are registering 6 different listeners, and none of them fire after the initial period.  

All of my event listeners are at the top-level of my background.js and that is at the root of my extension files. 

Expected behavior: The service workers are reactivated when a new event is received. 

Screenshots below include folder structure, manifest, and listeners. 

**To Reproduce**
Steps to reproduce the behavior, or file the issue is found in:
1. Extension installed
2. Extension service workers inactive 
3. Execute browser event that should be caught be addListener() 

**Expected behavior**
Listeners capture new events and service worker switches back to (active) status. 

**Screenshots**
![event-listeners](https://user-images.githubusercontent.com/54776782/114450819-7a13ec80-9ba4-11eb-8016-bb16a9534cec.png)
![manifest](https://user-images.githubusercontent.com/54776782/114450828-7d0edd00-9ba4-11eb-9f83-8350d57962eb.png)

**Notes**
Manifest and subset of background.js can be found above.

**Comment by dotproto** [comment]
This issue appears to describe a Chrome bug rather than a bug report or feature request for the chrome-extensions-samples repository. Please visit https://crbug.com/new to file a bug report.

**Comment by mspencer** [comment]
@casendler Hi. Have you found a solution? I have an issue with 
chrome.runtime.onMessageExternal.addListener
Where it seems to run the sendResponse callback, but not the code in between.
Thanks

**Comment by jpmedley** [comment]
Chrome 110 (beta on Feb 7) changes how service worker timeouts occur. I should have an article with details published by the end of the day. The URL will be this: https://developer.chrome.com/blog/longer-esw-lifetimes
