### ISSUE TITLE
Broken link to extension examples in README

### ISSUE THREAD

**Issue by mikemklee** [GoogleChrome/chrome-extensions-samples#592]
**Describe the bug**
Broken link to extension examples in README

**To Reproduce**
1. Go to `Samples` [section](https://www.youtube.com/watch?v=lh9ustWLX6c&ab_channel=OdeStudioSeoul) in README
2. Click on link labeled `/extensions`
3. See 404 page

**Expected behavior**
1. link to extension examples should be renamed to `/examples` (?)
2. clicking on the link should not lead to 404 page

**Screenshots**
![image](https://user-images.githubusercontent.com/17537040/116819240-31b17400-ab3d-11eb-9e05-77c97a4e2f40.png)

**Notes**
I think the correct link is now this? I am not 100% sure, so please confirm:
https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/examples

**Comment by codetheorist** [comment]
This should now be closed as the link has been fixed.

**Comment by patrickkettner** [comment]
closing as it was fixed
