### ISSUE TITLE
chrome.search example

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/chrome-extensions-samples#605]
Are there any examples of `chrome.search` https://developer.chrome.com/docs/extensions/reference/search/?

**Comment by dabjulmaros** [comment]
is there a link to the search api example? 
doing
`"permissions": ["search"]`
in the manifest and
```
 chrome.search.query(
      { text: document.querySelector('input').value }
    ).then(e => console.log(e))
```
in my script returns 
`Cannot read properties of undefined (reading 'query')`

**Comment by dabjulmaros** [comment]
Found the solution.
To be able to use the search api you also need to have permission to the tabs api.
so to fix my code all I had to do was modify my manifest to add
`"permissions": ["tabs","search"]`
If that information is mentioned anywhere in the search api reference Im blind cause I didnt saw it.

**Comment by jpmedley** [comment]
I'm not sure why this was closed, since we don't have a search example.

**Comment by jpmedley** [comment]
cc: @patrickkettner

**Comment by Pask00** [comment]
I would like to write a sample for this!

My idea is the following: clicking on the icon extension a popup will appear, from there you can type the search query and choose where it should be opened (current tab, new tab etc.).

**Comment by locallhostcl** [comment]
![Uploading KYC.png…]()
