### ISSUE TITLE
Typo on action demo index page

### ISSUE THREAD

**Issue by danwahl** [GoogleChrome/chrome-extensions-samples#621]
There's a typo on [this line](https://github.com/GoogleChrome/chrome-extensions-samples/blob/130a2a5d6445b34b2bb30fc8236b4f2884039507/api/action/demo/index.html#L49): "We _chan_ change..."

**Comment by adityadees** [comment]
> There's a typo on [this line](https://github.com/GoogleChrome/chrome-extensions-samples/blob/130a2a5d6445b34b2bb30fc8236b4f2884039507/api/action/demo/index.html#L49): "We _chan_ change..."

done with #628
