### ISSUE TITLE
It seems alarms is not working in V3

### ISSUE THREAD

**Issue by silvioprog** [GoogleChrome/chrome-extensions-samples#630]
**Problem**

It seems the alarms are never triggered.

**Chrome version**

Version 92.0.4515.159 (Official Build) (64-bit) (Ubuntu 20.04)

**Example**

Consider this manifest:

```js
// manifest.json

{
  "name": "My alarm",
  "description": "My alarm example",
  "version": "1.0",
  "manifest_version": 3,
  "background": {
    "service_worker": "background.js"
  },
  "action": {},
  "permissions": ["alarms"]
}
```

and this background script:

```js
// background.js

let count = 1;

chrome.alarms.onAlarm.addListener(() => {
  chrome.action.setBadgeText({ text: count.toString() });
  count++;
});

chrome.runtime.onInstalled.addListener(() => {
  chrome.action.setBadgeText({ text: count.toString() });
  chrome.alarms.create("alarm", { periodInMinutes: 1 });
});
```

**Steps to reproduce**

1. Install the extension
2. Notice the badge `1` is showed in the extension icon
3. While for 1 minute or more

Notice even after 1 minute, the icon stills showing `1` as picture below, but it should show `2`, since an alarm was created and listened.

![Screenshot from 2021-08-26 13-27-44](https://user-images.githubusercontent.com/1456829/131000379-328db406-c140-4631-a665-9e5328ac4585.png)

P.S.: Even after closing Chrome, reopening it and waiting for 1 minute or more, neither badge `1` or `2` is never shown.

**Comment by samthor** [comment]
Yes—sorry, we should have noticed this too.

This is a big gotcha for extension developers. MV3 Service Workers are entirely event-based and there's no guarantee of lifetime. This gives Chrome much more freedom to kill/restart your code as nessecary, which is good for performance.

**Comment by nnayk** [comment]
Is there a way to set the time period to 1 second? Based on what I've seen it seems the minimum for periodInMinutes is 1 minute. I am trying to build a stopwatch extension but I am running into this roadblock.
