### ISSUE TITLE
You should be able to open an `<iframe>` with URL set to `chrome-extension://<id>/file.html` by specifying the file in `"web_accessible_resources"` then use `navigator.mediaDevices.getUserMedia()` and `navigator.mediaDevices.getDisplayMedia()`.

### ISSUE THREAD

**Issue by Thiri25** [GoogleChrome/chrome-extensions-samples#632]
You should be able to open an `<iframe>` with URL set to `chrome-extension://<id>/file.html` by specifying the file in `"web_accessible_resources"` then use `navigator.mediaDevices.getUserMedia()` and `navigator.mediaDevices.getDisplayMedia()`.

_Originally posted by @guest271314 in https://github.com/GoogleChrome/chrome-extensions-samples/issues/627#issuecomment-898934924_

**Comment by guest271314** [comment]
What is the issue?
