### ISSUE TITLE
Update Native Messaging API sample to MV3

### ISSUE THREAD

**Issue by Edgoze** [GoogleChrome/chrome-extensions-samples#644]
We are trying to build a program that would be able to communicate with extensions on a remote computer without having to install something. 

However, it looks like the Chrome API has been updated and thus the functions we intended to use are now obsolete. Is there any way for us to find similar functions?

Thanks in advance!

**Comment by guest271314** [comment]
Native Messaging is not obsolete.

**Comment by sefirosweb** [comment]
The example of manifest version 2 still works?

https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/mv2-archive/api/nativeMessaging

I'm trying but chrome tell me only i can upload a version 3

**Comment by guest271314** [comment]
An example with MV3 using Python host is in this PR https://github.com/GoogleChrome/chrome-extensions-samples/pull/617.

**Comment by sefirosweb** [comment]
@guest271314 cool thanks i got it!

I have ready my small extension :D

**Comment by oliverdunk** [comment]
Native Messaging is still supported and we recently reviewed the documentation here: https://developer.chrome.com/docs/extensions/mv3/nativeMessaging/

However, our sample (which should still work for the most part) is currently based on MV2: https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/_archive/mv2/api/nativeMessaging. We should update this to MV3 and confirm it continues to work.

**Comment by Shubham-Rasal** [comment]
This PR fixes the issue. Though not sure whether the old one is still requiredred or not.
