### ISSUE TITLE
Unchecked runtime.lastError: Error when communicating with the native messaging host.

### ISSUE THREAD

**Issue by 1004589696** [GoogleChrome/chrome-extensions-samples#648]

**Comment by 1004589696** [comment]
// index.js


var stream = require('stream');
var util = require('util');

function Input() {
    stream.Transform.call(this);

    // Transform bytes...
    this._writableState.objectMode = false;
    // ...into objects.
    this._readableState.objectMode = true;

    // Unparsed data.
    this.buf = typeof Buffer.alloc === 'function' ? Buffer.alloc(0) : new Buffer(0);
    // Parsed length.
    this.len = null;
}

util.inherits(Input, stream.Transform);

Input.prototype._transform = function(chunk, encoding, done) {
    // Save this chunk.
    this.buf = Buffer.concat([ this.buf, chunk ]);

    var self = this;

    function parseBuf() {
        // Do we have a length yet?
        if (typeof self.len !== 'number') {
            // Nope. Do we have enough bytes for the length?
            if (self.buf.length >= 4) {
                // Yep. Parse the bytes.
                self.len = self.buf.readUInt32LE(0);
                // Remove the length bytes from the buffer.
                self.buf = self.buf.slice(4);
            }
        }

        // Do we have a length yet? (We may have just parsed it.)
        if (typeof self.len === 'number') {
            // Yep. Do we have enough bytes for the message?
            if (self.buf.length >= self.len) {
                // Yep. Slice off the bytes we need.
                var message = self.buf.slice(0, self.len);
                // Remove the bytes for the message from the buffer.
                self.buf = self.buf.slice(self.len);
                // Clear the length so we know we need to parse it again.
                self.len = null;
                // Parse the message bytes.
                var obj = JSON.parse(message.toString());
                // Enqueue it for reading.
                self.push(obj);
                // We could have more messages in the buffer so check again.
                parseBuf();
            }
        }
    }

    // Check for a parsable buffer (both length and message).
    parseBuf();

    // We're done.
    done();
};

function Output() {
    stream.Transform.call(this);

    this._writableState.objectMode = true;
    this._readableState.objectMode = false;
}

util.inherits(Output, stream.Transform);

Output.prototype._transform = function(chunk, encoding, done) {
    var len = typeof Buffer.alloc === 'function' ? Buffer.alloc(4) : new Buffer(4);
    var buf = typeof Buffer.from === 'function'
        ? Buffer.from(JSON.stringify(chunk))
        : new Buffer(JSON.stringify(chunk));

    len.writeUInt32LE(buf.length, 0);

    this.push(Buffer.concat([len, buf]));

    done();
};

function Transform(handler) {
    stream.Transform.call(this);

    this._writableState.objectMode = true;
    this._readableState.objectMode = true;

    this.handler = handler;
}

util.inherits(Transform, stream.Transform);

Transform.prototype._transform = function(msg, encoding, done) {
    this.handler(msg, this.push.bind(this), done);
};

function Debug() {
    stream.Transform.call(this);

    this._writableState.objectMode = true;
    this._readableState.objectMode = false;
}

util.inherits(Debug, stream.Transform);

Debug.prototype._transform = function(chunk, encoding, done) {
    this.push(JSON.stringify(chunk) + '\n');

    done();
};

exports.Input = Input;
exports.Output = Output;
exports.Transform = Transform;
exports.Debug = Debug;

**Comment by guest271314** [comment]
Can you post the code, here?

**Comment by 1004589696** [comment]
// background.js
`
chrome.runtime.onMessage.addListener(function (request, sender, callback) {
  console.log('background:', request.content);

  var hostName = "com.google.chrome.securitycontrols.electron";
  var port = chrome.runtime.connectNative(hostName);

  port.onMessage.addListener((message) => {
    console.log('onRecvNativeMessage');
    console.log(message)
    callback("from background.js to main.js");
    console.log('onRecvNativeMessage=====end');
  });


  port.onDisconnect.addListener(() => {
    console.log('onDisconnected');
    port = null;
  });

  
  port.postMessage({ text: "a,b,c,d" });
  callback("from background.js to main.js");
});


`

`{
    "name": "com.google.chrome.securitycontrols.electron",
    "description": "Chrome Native Messaging API Example Host",
    "path": "/Library/Google/Chrome/NativeMessagingHosts/security-controls-pkg",
    "type": "stdio",
    "allowed_origins": [
        "chrome-extension://mgcjafdofkofijefcpfcaefblidfabko/"
    ]
}
`

`
const { Transform } = require('stream');

const commaSplitter = new Transform({
    readableObjectMode: true,

    transform(chunk, encoding, callback) {
        this.push(chunk.toString().trim().split(','));
        callback();
    }
});

const arrayToObject = new Transform({
    readableObjectMode: true,
    writableObjectMode: true,

    transform(chunk, encoding, callback) {
        const obj = {};
        for (let i = 0; i < chunk.length; i += 2) {
            obj[chunk[i]] = chunk[i + 1];
        }
        this.push(obj);
        callback();
    }
});

const objectToString = new Transform({
    writableObjectMode: true,

    transform(chunk, encoding, callback) {
        this.push(JSON.stringify(chunk) + '\n');
        callback();
    }
});

process.stdin
    .pipe(commaSplitter)
    .pipe(arrayToObject)
    .pipe(objectToString)
    .pipe(process.stdout)
`

**Comment by guest271314** [comment]
Are you sure the Native Messaging host protocol is being implemented properly? 

Are you using Node.js?

If yes, I would try using https://github.com/simov/native-messaging as a template.

**Comment by 1004589696** [comment]
process.stdin
    .pipe(commaSplitter)
    .pipe(arrayToObject)
    .pipe(objectToString)
    .pipe(process.stdout) // problem runtime.lastError: Error when communicating with the native messaging host

=>

process.stdin.pipe(process.stdout)    // no problem

**Comment by 1004589696** [comment]
{
            "name": "智秒安全插件",
            "version": "6.0.0",
            "manifest_version": 3,
            "description": "使用本插件实现从指定PC登陆系统",
            "icons": {
              "16": "icon-16.png",
              "128": "icon-128.png"
            },
            "background": {
              "service_worker": "background.js"
            },
            "content_scripts": [
              {
                "matches": [
                  "*://*.100youdian.com/*",
                  "*://*.miaoerp.com/*"
                ],
                "js": [
                  "main.js"
                ],
                "run_at": "document_end"
              }
            ],
            "permissions": [
              "storage",
              "declarativeContent",
              "nativeMessaging"
            ],
            "externally_connectable": {
              "matches": ["*://*.100youdian.com/*", "*://*.miaoerp.com/*"]
            }
          }

**Comment by guest271314** [comment]
Native Messaging protocol expects JSON; escaped when necessary. What is the JSON that you are sending from Native Messaging host? 

Is the message a string, array, or object?

If the message is a string, are there unescaped double quotes included in the string, or not surrounding the string?

**Comment by 1004589696** [comment]
port.postMessage("a,b,c,d");

**Comment by guest271314** [comment]
What does the Native Messaging host expected to output to Native Messaging client?

**Comment by 1004589696** [comment]
{a: b, c: d}

**Comment by guest271314** [comment]
That does not appear to be valid JSON. Is the requirement to remove double quotes?

```
'{"a":"b","c":"d"}'
```

**Comment by 1004589696** [comment]
> What does the Native Messaging host expected to output to Native Messaging client?

object

**Comment by 1004589696** [comment]
> What does the Native Messaging host expected to output to Native Messaging client?

{a:"b", c:"d"}

**Comment by guest271314** [comment]
Have you tried removing `+ '\n'` following `JSON.strinigfy()`?

**Comment by 1004589696** [comment]
> Have you tried removing `+ '\n'` following `JSON.strinigfy()`?

Still not

**Comment by guest271314** [comment]
Where do you send message length preceding message per the Native Messaging protocol?

https://developer.chrome.com/docs/apps/nativeMessaging/#native-messaging-host-protocol
The same format is used to send messages in both directions: each message is serialized using JSON, UTF-8 encoded and is preceded with 32-bit message length in native byte order. 

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging#app_side
> Each message is serialized using JSON, UTF-8 encoded and is preceded with an unsigned 32-bit value containing the message length in native byte order.

**Comment by oliverdunk** [comment]
I'm going to close this for now. If you still need help, feel free to start a conversation here: https://groups.google.com/a/chromium.org/g/chromium-extensions
