### ISSUE TITLE
Need a simple example just showing how to open a new tab with the Tabs API

### ISSUE THREAD

**Issue by cryswerton** [GoogleChrome/chrome-extensions-samples#654]
I think it might be really useful to add an example demonstrating how to open a new tab with a HTML document in it.

**Comment by AmySteam** [comment]
In the meantime, here's a code sample of how to open an HTML page when the user first installs the extension:

[Opening an extension page in a new tab](https://developer.chrome.com/docs/extensions/reference/tabs/#opening-an-extension-page-in-a-new-tab)

**Comment by oliverdunk** [comment]
I think this should be covered by this sample: https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/api-samples/tabs/inspector. If you spot anything missing, please feel free to open a new issue!
