### ISSUE TITLE
is there any methods to control the border radius of popup.html? 

### ISSUE THREAD

**Issue by laulliam** [GoogleChrome/chrome-extensions-samples#657]
is there any methods to control the border radius of popup.html?

**Comment by compiled-krishan** [comment]
This is not possible in the current manifest versions. May be we can see updates on this in future from google.

**Comment by hunterphillips** [comment]
Everything I've seen says its not possible, but it looks like the Google Keep extension is pulling it off (can see in the 3rd screenshot)

https://chrome.google.com/webstore/detail/google-keep-chrome-extens/lpcaedmchfhocbbapmcbpinfpgnhiddi?hl=en

**Comment by patrickkettner** [comment]
Checking out [ the code](https://robwu.nl/crxviewer/?crx=https://chrome.google.com/webstore/detail/lpcaedmchfhocbbapmcbpinfpgnhiddi), you will see it is not using a popup. They are injecting an iframe into the page, and styling that.

**Comment by Vedbhanushali** [comment]
@patrickkettner it is confusing I checked the code it seems like compiled code, can you share an example of achieving this or source code reference.

**Comment by patrickkettner** [comment]
An example of what? They aren’t doing what the OP thought they were doing.

**Comment by Vedbhanushali** [comment]
@patrickkettner  you mean that using content.js they are injecting iframe in current tab instead of using popup.html

**Comment by NoamRivlin** [comment]
have mv3 made this possible or is it still not possible to control?

**Comment by oliverdunk** [comment]
Hi @NoamRivlin, there aren't any changes here I'm afraid.

**Comment by Visalan-H** [comment]
sad

**Comment by iamOmarFaruk** [comment]
It's possible to ignore popup.html and inject a layout through background.js. I just👨🏻‍💻 did it.

`chrome.action.onClicked.addListener((tab) => { // Get the current tab ID
  const tabId = tab.id;
  
  // Inject the content script into the current tab
  chrome.scripting.executeScript({
    target: { tabId: tabId },
    files: ['content.js']
  });
  
  console.log(`Content script injected into tab ${tabId}`);
}); `

and write the popup layout and inject in the current page, its basically a injected dom element 😁 

<img width="563" alt="Image" src="https://github.com/user-attachments/assets/e63898fc-b026-42b4-a5ce-cd7daef8c500" />

**Comment by Obsessive-Curiosity** [comment]
thanks!
