### ISSUE TITLE
Passing data from contentjs to popupjs using execute scripting

### ISSUE THREAD

**Issue by taouichaimaa** [GoogleChrome/chrome-extensions-samples#668]
**Describe the bug**
Hi, I need a more detailed example of passing data from content to popup using chrome execute scripting, most examples I found are to update the dom but I want to update the popup html itself with the data from contentjs. I tried using chrome.storage.local but it's not working.

**To Reproduce**
Steps to reproduce the behavior, or file the issue is found in:

**Expected behavior**

**Screenshots**

**Notes**
Anything additional here. 🌈

**Comment by guest271314** [comment]
Can you post what you have tried here?

**Comment by Ambushfall** [comment]
Pass variables with messages or store in storage properly.
Either listen to on message or on storage changed.

Fill out your template next time, please
