### ISSUE TITLE
Question on using sandbox in manifest v3

### ISSUE THREAD

**Issue by ForeverAT** [GoogleChrome/chrome-extensions-samples#669]
I can only find example using iframe to load sandbox.html in manifest v2. However, since manifest v3 service background will not aloud to access iframe, may I ask how should I load a sandbox.html?

**Comment by nbouteme** [comment]
@guest271314 care to provide a more specific example? Service workers in MV3 don't have access to a DOM, except injecting inside of already existing pages, but code running in those cannot even use chrome.runtime.connect to communicate efficiently with the service worker.

**Comment by guest271314** [comment]
It is possible to communicate with `ServiceWorker` 

- Using `"externally_connectable"`
- Using `"web_accesible_resources"` to append an `<iframe>` into the DOM an an arbitrary web site, where the `src` is `chrome-extension:`, thus communication is possible with `onmessage` and `clients.matchAll({includeUncontrolled: true})` in `ServiceWorker` and `navigator.serviceWorker.onmessage` in the JavaScript in the `<iframe>` thatcan communicate with the `parent` DOM with `postMessage()`

See the Chromium extensions at https://github.com/guest271314/persistent-serviceworker.

Other approaches exist as well.

**Comment by ForeverAT** [comment]
@guest271314 I would like to use some library like tesseract.js, opencv in my chrome extension, which is successful for mv2. When I am transferring to MV3, it is blocked because of unsafe-eval and access of DOM. For tesseract, which blocked by unsafe-eval, I am thinking whether it is able to use sandboxed page to insert. May I ask is this possible and how should I do?

**Comment by guest271314** [comment]
I have not tried tesseract.js.

I have removed `Content-Security-Policy` headers altogether in order to `fetch()` localhost on any website https://github.com/guest271314/remove-csp-header.

You can use `"web_accessible_resources"` to `import` scripts from the extension to web pages listed in `"matches"`.

**Comment by guest271314** [comment]
Let's say your `"web_accessible_resources"` entry looks something like 

```
  "web_accessible_resources": [{
      "resources": [ "*.html", "*.js"],
      "matches": [ "<all_urls>" ],
      "extensions": [ ]
  }],
```

You can now append an `<iframe>` to any arbitrary web page with `src` set to `chrome-extension://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/ext.html` (your extension).

```
<script src="tesseract.js"></script>
```

where `tesseract.js` is in the extension directory.

In `tesseract.js` you can communicate with both the `ServiceWorker` and the DOM that the `<iframe>` was appended to.

Inject a script in the `parent` using `scripting.executeScript()`

`onmessage = (e) => console.log(e.data)`

In `tesseract.js` post to the page 

`parent.postMessage(data, url_of_web_page)`

That is one way to achieve what you are trying to do.

**Comment by ForeverAT** [comment]
@guest271314 Thank you for your response. I have two question on it. First, for the remove csp, I have read the file and I am slightly confused. Is this mean that with the rule_1.json, we can be not limited by unsafe-eval and use it in MV3 for extension page? Second question is that the tesseract.js is a library. I am not sure we can add postMessage in a library file, but I wish to import the library in a sandboxed page, is there any idea?

**Comment by nbouteme** [comment]
I think the "option" that interests most people is one that would allow to `eval` arbitrary strings, which is, to my knowledge, only possible within sandboxed pages, which are, to my knowledge, only possible under MV3 by injecting them inside of an iframe on a website.

The fact that this hasn't happened to you yet is irrelevant, the mere possibility of it is enough to dissuade most people to pursue this option as it'd give site owners the power to disable or severely impair extension functionality for some of their users. This is simply not acceptable.

**Comment by guest271314** [comment]
> The fact that this hasn't happened to you yet is irrelevant, the mere possibility of it is enough to dissuade most people to pursue this option as it'd give site owners the power to disable or severely impair extension functionality for some of their users. This is simply not acceptable.

Perhaps you do not gather that when I remove CSP hears I can request and execute scripts from anywhere.

I just don't need to do that when I use Native Messaging.

You could go a step further and run WebRTC datachannels on the OS and create a datachannel on any arbitrary page to commuinacate that way, too.

**Comment by guest271314** [comment]
@ForeverAT What are you trying to achieve that you are not able to do? What is the code?

**Comment by ForeverAT** [comment]
@guest271314 I am trying to use tesseract.js to obtain some information from the website. I have used several method for image preprocessing and use tesseract for OCR. In mv2, i used it in background script.

**Comment by guest271314** [comment]
What happens when you try to use tesseract.js with MV3? 

Does 

`import Tesseract from 'tesseract.js';` 

not import the script to the `ServiceWorker`?

**Comment by ForeverAT** [comment]
The unsafe-eval will pop up and extension not able to be loaded

**Comment by guest271314** [comment]
Using `import` in the `ServiceWorker`? With `type` set to `"module"`? Can you kindly post the manifest.json andcode that throws here?

**Comment by guest271314** [comment]
One issue with loading tessaract.min.js in a `ServiceWorker` is that `document` is used in the scripts at 

```
var t = document.createElement("base");
```

and several other times.

**Comment by guest271314** [comment]
I downloaded https://unpkg.com/tesseract.js@2.0.0/dist/tesseract.min.js to the extension directory, then tested the code below. If necessary you can communicate with the `ServiceWorker` using `"externally_connectable"`.

manifest.json
```
{
  "name": "Scripting, externally connectable",
  "version": "1.0",
  "manifest_version": 3,
  "permissions": ["tabs", "scripting"],
  "host_permissions": ["https://github.com/*"],
  "background": {
    "service_worker": "background.js"
  },
  "action": {},
  "externally_connectable": {
    "matches": [
      "https://github.com/*"
    ],
    "ids": [
      "*"
  ]}
}
```

background.js
```
let port;

function handleConnectExternal(_) {
  port = _;
  function handleMessage(e) {
    console.log(e);
  }
  function handleDisconnect(e) {
    console.log(e);
    port.onMessage.removeListener(handleMessage);
    port.onDisconnect.removeListener(handleDisconnect);
    port = null;
  }

  port.onMessage.addListener(handleMessage);
  port.onDisconnect.addListener(handleDisconnect);
}

chrome.runtime.onConnectExternal.addListener(handleConnectExternal);
chrome.action.onClicked.addListener(async (tab) => {
  console.log(tab);
  await chrome.scripting.executeScript({
    target: {
      tabId: tab.id,
    },
    world: 'MAIN',
    files: ['tesseract.min.js'],
  });
  await chrome.scripting.executeScript({
    target: {
      tabId: tab.id,
    },
    world: 'MAIN',
    args: [chrome.runtime.id],
    func: (id) => {
      port = chrome.runtime.connect(id, { name: 'tesseract' });
      console.log(port);
      port.onMessage.addListener((e) => { 
        console.log(e);
      });
      port.onDisconnect.addListener((e) => console.log(e));
      port.postMessage('Tesseract' in globalThis);
    },
  });
});
```

**Comment by ForeverAT** [comment]
@guest271314 Thank you very much for your help. After I implement the connect in my background script, I can use the tesseract package in background script?
```
port = chrome.runtime.connect(id, { name: 'tesseract' });
      console.log(port);
      port.onMessage.addListener((e) => { 
        console.log(e);
      });
      port.onDisconnect.addListener((e) => console.log(e));
      port.postMessage('Tesseract' in globalThis);
```
I am slightly confuse with this part. As tesseract is just a library, it does not use runtime.connect in tesseract.min.js, how it communicate with the background script?
Thank you very much for your support

**Comment by ForeverAT** [comment]
Sorry I may not be able to post the code here as related to research stuff, but really thanks for your help and sorry for the inconvenience.

> Using `import` in the `ServiceWorker`? With `type` set to `"module"`? Can you kindly post the manifest.json andc ode that throws here?

Sorry I may not post the code here as related to research stuff. Thanks a lot for your help and sorry for inconvenience.

**Comment by guest271314** [comment]
> @guest271314 Thank you very much for your help. 


No worries.

> After I implement the connect in my background script, I can use the tesseract package in background script?


No. tesseract.min.js  uses `document` in the script. `ServiceWorkerGlobalScope`, like `WorkerGlobalScope` and `DedicatedWorkerGlobalScope` do not have `document` defined.

> ```
> port = chrome.runtime.connect(id, { name: 'tesseract' });
>       console.log(port);
>       port.onMessage.addListener((e) => { 
>         console.log(e);
>       });
>       port.onDisconnect.addListener((e) => console.log(e));
>       port.postMessage('Tesseract' in globalThis);
> ```
> 
> I am slightly confuse with this part. As tesseract is just a library, it does not use runtime.connect in tesseract.min.js, how it communicate with the background script? Thank you very much for your support

In the function passed to `executeScript` notice that `port` is defined globally. You can access the variable `port` or `globalThis.port` from within the tesseract.js code you run.

Is the issue resolved?

**Comment by ForeverAT** [comment]
Yes, thanks a lot for your help. I will try to run the code these days. Thank you

**Comment by guest271314** [comment]
>  how it communicate with the background script?

background.js, the MV3 `ServiceWorker` just handles the icon click and executes the script in the tab clicked. The code is run in the clicked tab. If you need to send data outside of the `document` you can communicate with the "background.js" `ServiceWorker`.

**Comment by szmarczak** [comment]
@guest271314 ["externally_connectable"](https://developer.chrome.com/docs/extensions/mv3/manifest/externally_connectable/) refers to external resources, not a page of the Chrome Extension. Attaching `<iframe>` to the DOM of the current active tab works, but that's not the correct solution since the website has access to it. Also this forces you to have a non `chrome:` tab open. What if I just have `chrome://new-tab-page` open?

The [Manifest V3 Sandbox](https://developer.chrome.com/docs/extensions/mv3/manifest/sandbox/) docs have no example of how to do this. I couldn't find it in any other docs as well, which is kinda infuriating. The websites redirects us to [sandboxingEval](https://developer.chrome.com/docs/extensions/mv3/sandboxingEval/), which hasn't been updated to Manifest V3 yet.

**Comment by guest271314** [comment]
@szmarczak What are you trying to achieve?

**Comment by szmarczak** [comment]
Currently I'm creating an `<iframe sandbox="allow-same-origin">` (`sandbox` for security reasons, `allow-same-origin` required to access `iframe.contentDocument`) in my background page, then retrieving `iframe.contentDocument.body.innerText`.

There's https://github.com/w3c/webextensions/issues/72 to track Manifest V2 use cases not possible with the current state of Manifest V3.

**Comment by guest271314** [comment]
@szmarczak I am still trying to understand what you are trying to _do_?

**Comment by guest271314** [comment]
You can certainly utilize `"web_accessible_resources"` to embed an `<iframe>` in a target `document`, then access and communicate with the `<iframe>` from both the MV3 `ServiceWorker` and/or the arbitrary target document.

**Comment by guest271314** [comment]
@szmarczak See https://github.com/guest271314/persistent-serviceworker/blob/main/chromium_extension_web_accessible_resources_iframe_message_event/index.js

`"web_accessible_resources"` is defined in MV3 manifest.json.

On any arbitrary Web page, or specific Web page set an `<iframe>` is appended to the DOM of the target Web page.

When that happens `onfetch` event handler is fired in `ServiceWorker` and we can get a reference to the `<iframe>` in `ServiceWorker` with 

```
await self.clients.matchAll({ includeUncontrolled: true })
```
 and thereby communicate between the `<iframe>` and `ServiceWorker`.

Since the `<iframe>` is a child of `parent` we can also communicate with the target Web page with `onmessage` handler in the target document, so that we have a communication bridge between MV3 `ServiceWorker` and target Web page and the `<iframe>`

In pertinent part the JavaScript in the embedded `<iframe>` the functions as the bridge between MV3 `ServiceWorker` and target Web page

```
function closeMessageChannel() {
  parent.postMessage('close', name);
}
navigator.serviceWorker.oncontrollerchange = async (e) => {
  console.log(e);
  closeMessageChannel();
};
navigator.serviceWorker.onmessage = async (e) => {
  parent.postMessage(e.data, name, e.ports);
  try {
    while ((await navigator.serviceWorker.ready).active) {
      (await navigator.serviceWorker.ready).active.postMessage(null);
      await new Promise((resolve) => setTimeout(resolve, 1000 * 15));
    }
    closeMessageChannel();
  } catch (err) {
    console.error(err);
    closeMessageChannel();
  }
};
console.log(chrome.runtime);
```
