### ISSUE TITLE
Are there any other materials for learning mv3？

### ISSUE THREAD

**Issue by shaoshenchen** [GoogleChrome/chrome-extensions-samples#673]
It's challenging for me to learn only from developer.chrome.com, I use it as a dictionary.

So are there other materials to learn extension（**manifest version 3**）？thanks！！！

**Comment by guest271314** [comment]
What are you trying to achieve?

**Comment by shaoshenchen** [comment]
extension named IMG EDIT, it can capture image and web page, save them somewhere

**Comment by guest271314** [comment]
Basically take a screenshot of the page? 

See https://github.com/GoogleChrome/chrome-extensions-samples/issues/627, https://github.com/guest271314/screenshot.

**Comment by shaoshenchen** [comment]
thanks a lot
