### ISSUE TITLE
Hey 

### ISSUE THREAD

**Issue by jon1234567** [GoogleChrome/chrome-extensions-samples#676]
@[⚠️ If you're have general Chrome Extensions questions, consider posting to the [Chromium Extensions Group](https://a

**Describe the bug**
A clear@ and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior, or file the issue is found in:
@phuang @
**Expected behavior**@~~~~ x
> > > A clear and concise # # desc```~~the best 5 in ~~```**Screenshots**
If applicable, add Screenshot. Ato help explain your problem.
6
**Notes**[]()the most important thing to do is to make sure that you are not the only one who is 
> Anything additional 224 35 436 =here. 🌈
]()aquarium

**Comment by dotproto** [comment]
Closing as this issue does not contain a bug report or feature request.
