### ISSUE TITLE
```getBackgroundPage``` is still usable?

### ISSUE THREAD

**Issue by fxqy** [GoogleChrome/chrome-extensions-samples#702]
```chrome.extension.getBackgroundPage()``` is this api still usable? How to get the page of 'Service_Worker '

**Comment by fxqy** [comment]
mv2 will expire next year. I want to upgrade my extension to mv3, but I can't get the backgroundpage. I found the relevant api of aaa in mdn. Can I only communicate through message in the future?

[service_worker api in MDN](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/message_event)
![jietu_mingzi_2022-4-9_11-14-12](https://user-images.githubusercontent.com/42601163/162554307-ebdb66d9-78c8-493a-be1c-212bed302319.png)

**Comment by Ambushfall** [comment]
Service workers and Content Scripts are supposed to only communicate with messages.

You can although define a service worker as a module and import stuff into it.

Make sure you define, type module in manifest.

**Comment by M-SAI-SOORYA** [comment]
The chrome.extension.getBackgroundPage() API is still available in Chrome extensions, but it is not supported in the latest Manifest v3 (mv3) for Chrome extensions. Instead, you can use the chrome.runtime.getBackgroundPage() API, which is supported in mv3.

To communicate with a Service Worker in an extension, you can use the chrome.runtime.sendMessage and chrome.runtime.onMessage APIs. These APIs allow you to send and receive messages between different parts of your extension, including between content scripts, background scripts, and Service Workers.

**Comment by jpmedley** [comment]
`chrome.runtime.getBackgroundPage()` is not supposed to work either. If it works for you, it's a bug. Can you share your use case? We can help you find another code path.

**Comment by oliverdunk** [comment]
Closing this one since this is no longer a supported API. Messaging is definitely the way to go if you need communication between the service worker and another context.
