### ISSUE TITLE
[request] need a sample to create a "Router management" extension

### ISSUE THREAD

**Issue by sajati** [GoogleChrome/chrome-extensions-samples#719]
Unlike other huawei routers, B312-926 need a logged in user to view information like signal strength, etc.
i was thinking about creating an extension that can manage my huawei router even just to show signal strength but without loging in via tabs, i found this extension that works https://drive.google.com/file/d/1EViob6rDkCstc1h6dHUYZS8Zb-nHkH-D/view but it require log in via tabs, i was hoping to create **an extension that login directly from extension(not from tab) and perhaps save the credential to localstorage api to avoid logged out automatically.**
here's the known api's that may be used http://www.bez-kabli.pl/viewtopic.php?t=42168

**Comment by Ambushfall** [comment]
It's a big No No when you include obfuscated code, especially with google drive links or polish websites.

Yes, it's possible, it's not smart to do so, however and requires a bunch of tricks.

You have to know your router in and out in terms of it's localhosted server.
