### ISSUE TITLE
Clicking on the error button is invalid

### ISSUE THREAD

**Issue by flashclub** [GoogleChrome/chrome-extensions-samples#735]
**Describe the bug**
The page did not jump after clicking Errors button.

**To Reproduce**
1. Enter the code into the serviceworker file：
```javascript
const num = 0;
num++;
```
2. Extension show Errors button
3. Click Errors button the page didn't show errors detail
4. The Errors button didn't disappear when I fix the obvious bug and refresh extension

**Expected behavior**
When I click on Errors I can display the details

**Screenshots**
The link has changed but no error details are displayed
![image](https://user-images.githubusercontent.com/30818149/178696571-f4de7747-23d6-409a-9947-307dd400c12c.png)

**Notes**
This issue is triggered by a specific error. If I use `chrome.action` and don't declare the action in the manifest, the Errors button appears, but I can click it to see the details normally. And when I reassign a constant to a constant, the Errors button shows but cannot be clicked; to get rid of the Errors button, I must remove the plugin, update the code, and then load the plugin again.

**Comment by Ambushfall** [comment]
> **Describe the bug** The page did not jump after clicking Errors button.
> 
> **To Reproduce**
> 
> 1. Enter the code into the serviceworker file：
> 
> ```js
> const num = 0;
> num++;
> ```
> 
> 2. Extension show Errors button
> 3. Click Errors button the page didn't show errors detail
> 4. The Errors button didn't disappear when I fix the obvious bug and refresh extension
> 
> **Expected behavior** When I click on Errors I can display the details
> 
> **Screenshots** The link has changed but no error details are displayed ![image](https://user-images.githubusercontent.com/30818149/178696571-f4de7747-23d6-409a-9947-307dd400c12c.png)
> 
> **Notes** This issue is triggered by a specific error. If I use `chrome.action` and don't declare the action in the manifest, the Errors button appears, but I can click it to see the details normally. And when I reassign a constant to a constant, the Errors button shows but cannot be clicked; to get rid of the Errors button, I must remove the plugin, update the code, and then load the plugin again.

I've had an issue where the error would keep showing up if I had caused type errors or in general had bad error handling.

If the extension works regularly with valid code, it shouldn't have this issue.


Also, is there a reason you are incrementing a non mutable value?

**Comment by patrickkettner** [comment]
Thank you for the report, but this is a repo for the samples being provided. Please report issues with Chrome on crbug.com
