### ISSUE TITLE
when doing console.log(chrome.tabs) is it supposed to return undefined

### ISSUE THREAD

**Issue by AhnafS** [GoogleChrome/chrome-extensions-samples#736]
every time i try to do `chrome.tabs.query` it always says that it cannot read undefined. I tried doing `console.log(chrome.tabs)` and found that it also gave undefined. Is this supposed to be the case?

**Comment by Ambushfall** [comment]
For future notice, can you please add some code in context?

If you're calling it without the proper parameters, or in the wrong location it could very much return undefined if no tab is open.

Thanks!

**Comment by patrickkettner** [comment]
Closing as @AhnafS did not share any code.
