### ISSUE TITLE
Milestones extension example does not render when installed into Chrome 

### ISSUE THREAD

**Issue by DominicFinn** [GoogleChrome/chrome-extensions-samples#752]
**Describe the bug**
The milestones chrome extension doesn't render when installed and clicked on in Chrome. 

**To Reproduce**
Clone repository from main. Go to chrome://extensions/ and install the unpacked extension "milestones". Click on extension in chrome. 

View console in Chrome, see error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'match')
    at getMilestone (popup.js:23:21)
    at popup.js:15:49
```

**Expected behavior**
A working miletones chrome extension. I can't speak to how it's supposed to look as it's not worked first time. 

**Screenshots**
![Screenshot 2022-09-09 at 11 37 31](https://user-images.githubusercontent.com/697551/189332086-ce12612d-0b91-4b6a-90bb-449f85423d53.png)

Chrome version: 
`Version 105.0.5195.102 (Official Build) (x86_64)`

Platform: 
macOS Montery
version 12.3.1

**Comment by DominicFinn** [comment]
It looks like a missing permission actually in the manifest: https://developer.chrome.com/docs/extensions/reference/tabs/

**Comment by oliverdunk** [comment]
I had a quick look here and the extension seems to be working as I'd expect. For example, if I go to:

https://chromium-review.googlesource.com/c/chromium/src/+/4181874

And then open the popup, the popup shows that it was first seen in Chrome 112.

From the README:

- This extension only works on https://chromium-review.googlesource.com/.
- "If the CR has not yet been merged or if the extension cannot find the version it was merged into, the action popup will automatically close itself."

@DominicFinn, is it possible you were hitting one of these? :)
