### ISSUE TITLE
Prepare for the future with Google Analytics 4

### ISSUE THREAD

**Issue by fieropheonix6** [GoogleChrome/chrome-extensions-samples#759]
https://blog.google/products/marketingplatform/analytics/prepare-for-future-with-google-analytics-4/

**Comment by capooghaith** [comment]
Hi @fieropheonix6 , hope everything os fine with you. 
I got a question regarding GA4 implementation in chrome extension, is there a sophisticated way so far to add it like it used to be with UA?
Thank you in advance

**Comment by patrickkettner** [comment]
[A sample for this was added in June](https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/functional-samples/tutorial.google-analytics)
