### ISSUE TITLE
Add samples for complex migrations

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/chrome-extensions-samples#763]
**Describe the bug**
The [MV3 migration guide](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/) does not currently have a sample manifest.json file, but it should. 

At minimum, this page should contain an example of migrating from a background script to a service worker. We may want to expand samples to show more complex migrations, such as a custom background.html or an array of scripts.

**Comment by sebastianbenz** [comment]
Not sure if there's too much value in having a sample for this. The problem with complex migrations is that they're - wait for it - complex. Samples should be focused and avoid complexity. 

Closing this for now, however, if there are specific use cases of a complex migration that are worth having a sample for, we should create individual issues for tracking these.
