### ISSUE TITLE
[samples] Internal examples: cherry pick and bring those into the samples repo/docs

### ISSUE THREAD

**Issue by awfuchs** [GoogleChrome/chrome-extensions-samples#764]
We need useful examples of MV3 extensions. There are some internally-developed examples that may be suitable for use or adaptation as public examples. Cherry pick and include examples into the MV3 examples corpus as appropriate.

**Comment by M-SAI-SOORYA** [comment]
some useful examples of MV3 extensions that you can adapt or use as inspiration for your own projects:

uBlock Origin: This popular ad blocker is built using Manifest V3 and demonstrates how to use the new declarativeNetRequest API to block network requests. The source code for uBlock Origin is open source and can be found on GitHub.

OneTab: This extension is a tab management tool that uses Manifest V3 and demonstrates how to use the new chrome.scripting API to insert content scripts into pages.

Dark Reader: This extension provides a dark mode for websites and demonstrates how to use the new chrome.declarativeContent API in Manifest V3 to create a declarative rule for injecting a content script.

**Comment by oliverdunk** [comment]
@jpmedley Thoughts on closing this? I'm not aware of anything internal that makes sense to share, and we're slowly getting there with MV3 samples, so I'm not sure this issue is relevant anymore.
