### ISSUE TITLE
Sample: Set opener on Window created with chrome.windows.create()

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/chrome-extensions-samples#778]
`setSelfAsOpener` option of `chrome.windows.create()` https://developer.chrome.com/docs/extensions/reference/windows/#method-create throws from MV3 `ServiceWorker`

```
Uncaught (in promise) Error: Cannot specify setSelfAsOpener Service Worker extension.
```
and is not defined in content scripts.

Sample request:  Set `opener` on `Window` created with `chrome.windows.create()`.

**Comment by guest271314** [comment]
There is currently no way to set `opener` for the `Window` created by `chrome.offscreen.createDocument()` either.

Sample request: Programmatically set `opener` on `Window` created with `chrome.offscreen.createDocument()`.

**Comment by patrickkettner** [comment]
Closing this out, feel free to follow along at https://crbug.com/1275145
