### ISSUE TITLE
Sample: Create Worker with src set to chrome-extension

### ISSUE THREAD

**Issue by guest271314** [GoogleChrome/chrome-extensions-samples#780]
**Describe the bug**
There does not appear to be any way to create a `Worker` or `SharedWorker` on a Web page with `src` set to `chrome-extension:` protocol.

**To Reproduce**
Steps to reproduce the behavior, or file the issue is found in:
1. `new Worker('chrome-extension:<id>')`
2. Error is thrown `Uncaught DOMException: Failed to construct 'Worker': Script at 'chrome-extension://<id>/worker.js' cannot be accessed from origin 'https://github.com'.`
3. manifest.json
```
  "web_accessible_resources": [{
      "resources": ["*.js"],
      "matches": ["<all_urls>"],
      "extensions": []
  }],
  "externally_connectable": {
    "matches": [
      "*://*.github.com/*"
    ],
    "ids": [
      "*"
  ]}
```

**Expected behavior**
`Worker` to load

**Screenshots**

**Notes**
This was apparently possible using MV2 https://chromium.googlesource.com/chromium/src.git/+/HEAD/chrome/test/data/extensions/api_test/worker/manifest.json

**Comment by patrickkettner** [comment]
This is working as intended.
