### ISSUE TITLE
Manifest V3 DeclarativeNetRequest to redirect Javascript request

### ISSUE THREAD

**Issue by stewartschillingsdi** [GoogleChrome/chrome-extensions-samples#784]
I maintain an extension that allows the swap `src` of the hard-coded Adobe Launch script tag on an HTML page to different hosted javascript file.  For example, a site might have 
`<script  src="https://assets.adobedtm.com/4faed591d364/86379f53529a/launch-73b5d63ca593.js" async></script>`
but the extension (using the WebRequest API) detects that request and redirects it to "https://assets.adobedtm.com/4faed591d364/86379f53529a/launch-123456789-devel.js" instead so that the development version of the file can be tested.

I have attempted to accomplish the same using declarativeNetRequest as shown below. 
manifest.json
```
{
  "name": "foo barrrrrr",
  "version": "0.0.1",
  "declarative_net_request": {
    "rule_resources": [
      {
        "id": "ruleset_1",
        "enabled": true,
        "path": "rules_1.json"
      }
    ]
  },
  "permissions": ["declarativeNetRequest"],
  "host_permissions": ["*://*/*"],
  "manifest_version": 3
}
```
rules_1.json
```
[
  {
    "id": 1,
    "priority": 1,
    "action": {
      "type": "redirect",
      "redirect": {
        "transform": {
          "path": "/4faed591d364/5abe43e091bf/launch-5505cf5f09f4-development.min.js"
        }
      }
    },
    "condition": {
      "urlFilter": "https://assets.adobedtm.com/4faed591d364/86379f53529a/launch-73b5d63ca593.js",
      "resourceTypes": ["script"]
    }
  }
]
```
When I use an action type of 'block'. The condition is met and the script file is blocked.  When I use 'redirect' as shown above, nothing happens.   If I am unable to write redirect actions for script resources, I will not be able to move this extension to manifest v3.  Is this the case?  Is there a workaround?

**Comment by guest271314** [comment]
I think there is something about redirects must use the same protocol in the documentation. So redirect from `https:` protocol needs to be to `https:` protocol, instead of `file:` or `chrome-extension:`.

What happens when you redirect to an `https:` protocol?

**Comment by stewartschillingsdi** [comment]
> I think there is something about redirects must use the same protocol in the documentation. So redirect from `https:` protocol needs to be to `https:` protocol, instead of `file:` or `chrome-extension:`.
> 
> What happens when you redirect to an `https:` protocol?

This redirect is a path transformation, so the protocol should remain the same as the original.

**Comment by guest271314** [comment]
It looks like `https://assets.adobedtm.com/4faed591d364/86379f53529a/launch-73b5d63ca593.js` is `404`. Do you have another two set of URL's to test?

**Comment by guest271314** [comment]
The request is redirected here. I tested on Chromium 110 on Linux.

```
[
  {
    "id": 1,
    "priority": 1,
    "action": {
      "type": "redirect",
      "redirect": {
        "transform": {
          "path": "/npm/jquery@3.2.1/dist/jquery.min.js"
        }
      }
    },
    "condition": {
      "urlFilter": "https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.js",
      "resourceTypes": ["script"]
    }
  }
```

Navigate to https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.js then run the following code in DevTools `console`, notice jquery.min.js is printed. At Network tab in DevTools the path is set to the minified file ste in rules `:path: /npm/jquery@3.2.1/dist/jquery.min.js`. 


```
var s = document.createElement('script');
s.src = 'https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.js';
document.body.appendChild(s);

console.log(await (await fetch(s.src)).text());
```

**Comment by stewartschillingsdi** [comment]
Thanks, @guest271314 
I don't know what I was doing wrong, but upon second inspection it seems to be working now.
I did update my `condition.urlFilter` and `redirect.transform.path` values, so perhaps it was just that simple.
