### ISSUE TITLE
In API Action demo, setIcon Reset can't work as current folder is demo.

### ISSUE THREAD

**Issue by szjfhb** [GoogleChrome/chrome-extensions-samples#790]
https://github.com/GoogleChrome/chrome-extensions-samples/blob/a0f47934ea5cc950a745b803d0d2a515a26ab43d/api/action/demo/index.js#L201

Here maybe we need reset the "current" path, seems not found the API so far.
Or, manual set the full path like:  chrome.runtime.getURL(manifest.action.default_icon[32]));

Thanks.

**Comment by oliverdunk** [comment]
I wasn't able to reproduce this. If you're still hitting it, feel free to re-open and I can take another look.

**Comment by rajeshmernstack** [comment]
chrome.action.setIcon({ path: "icon_16.png" });

This is solution, please make sure png file size is 16px
