### ISSUE TITLE
Broken Images

### ISSUE THREAD

**Issue by Nirmal222** [GoogleChrome/chrome-extensions-samples#800]
Hello Amy, I can see that a few of the images in the repository are broken. Please fix them.
Link: https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/tutorials/focus-mode/images

**Comment by AmySteam** [comment]
Hi @Nirmal222. Can you help me understand how these images are broken? Which sizes?

128x128 px seems to work.
https://github.com/GoogleChrome/chrome-extensions-samples/blob/main/tutorials/focus-mode/images/icon-128.png

**Comment by Nirmal222** [comment]
![Git Image](https://user-images.githubusercontent.com/33796030/211433581-fc7ed784-36f5-43fc-a4f0-0596dec2e1c4.JPG)
This is the case with the rest of them as well. I'm not sure if it is the problem with my Personal Device or from Repo. Please do have a check. Thankyou.

**Comment by AmySteam** [comment]
@Nirmal222 Thanks for sharing this screenshot :) That's super helpful 👍 

Have you tried cloning this repo? Do the images show up?
Does it happen with the other tutorial PNGs?
https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/tutorials/reading-time/images 

Next, I want to test this on a Windows computer and see if I can replicate it. Thanks again for reporting this 🙂

**Comment by Nirmal222** [comment]
No, I didn't try cloning I went on creating folders.
Yeah, there were other PNGs facing the same issue.
Yeah Hoping it would get fixed Sooner.
