### ISSUE TITLE
favicon sample, can't get it working in flutter

### ISSUE THREAD

**Issue by sgehrman** [GoogleChrome/chrome-extensions-samples#845]
It seems these favicon urls "chrome-extension://fmmdkgjgfgmeeblbfmgfmfkigjdcmjjc/_favicon/?pageUrl=...." only work inside an `<img>` tag.  I can't get it working in Flutter. 

Why do you provide favicons in this weird protected way?  Just let me download the bytes.  You put up road blocks on developers that don't make any sense. Totally useless feature.

This doc is for the 1990's.  Provide a modern way to get favicons. Removed these weird protection stuff.
https://developer.chrome.com/docs/extensions/mv3/favicon/

**Comment by patrickkettner** [comment]
I agree that there should be more information on why security and privacy things are in place, and I apologize that it has been frustrating. Favicons can reveal private information, as they can be customized to an individual person. Therefore you need the permission to access it. 

Why are you unable to access a URL within your Flutter code? What issue are you hitting?

**Comment by sebastianbenz** [comment]
Steve, do you use the html or canvas renderer for your flutter code? As the
html renderer uses the `img` tag under the hood, it should work.
