### ISSUE TITLE
Using Chrome extension to access the accessibility tree of an element

### ISSUE THREAD

**Issue by Lzy17** [GoogleChrome/chrome-extensions-samples#997]
Can a Chrome extension access the accessibility tree of an element on the current tab? For example, getting the accessibility list below

![image](https://github.com/GoogleChrome/chrome-extensions-samples/assets/36555117/f697657e-56c7-4cdd-a056-b69e2c1d158c)

**Comment by jpmedley** [comment]
Sorry for the late reply. 

I haven't had a chance to use it, so I can't say whether this answers your question. There is an Accessibility Features API. https://developer.chrome.com/docs/extensions/reference/accessibilityFeatures/

This issues page is for bugs in our samples. In the future please direct your questions to the extensions Google Group. If someone in the developer community can't answer your question, someone from Google will. https://groups.google.com/a/chromium.org/g/chromium-extensions

**Comment by sahil-lalani** [comment]
> Can a Chrome extension access the accessibility tree of an element on the current tab? For example, getting the accessibility list below
> 
> ![image](https://private-user-images.githubusercontent.com/36555117/262576788-f697657e-56c7-4cdd-a056-b69e2c1d158c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMDQ0MjksIm5iZiI6MTcxOTAwNDEyOSwicGF0aCI6Ii8zNjU1NTExNy8yNjI1NzY3ODgtZjY5NzY1N2UtNTZjNy00Y2RkLWEwNTYtYjY5ZTJjMWQxNThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDIxMDg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhNWYxZjA1NTRlYjY5ZmQxNmNmNjk0ZWVlODY1MTlhMjcxMGNkYjA3MGNkNmM2NTU2MTQ0ZDU4YjhkZmQ5NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q995w79NhPuQpZLz9pd6z074l2s9priz98o1tiFW7Ck)

hi were you able to figure this out and implement in a chrome extension?
