### ISSUE TITLE
Accessing and responding to the open/close state of a sidePanel

### ISSUE THREAD

**Issue by JeroenvdV** [GoogleChrome/chrome-extensions-samples#998]
Is there a way to retrieve the state of the extension's sidePanel: whether it is currently open or closed (in a certain tab)? Additionally, is there a way to listen to the event that this state changes?

Imagine I want to enable some functionality of a content script only when the sidePanel of the same extension is visible. Let's say showing the sidePanel makes the page's background color red, and closing the sidePanel reverts it back to normal. 

I could send a message from the sidePanel's html page to the service worker, which will hopefully indicate that it has opened, but I don't know how I can respond to the user closing the sidePanel.

**Comment by iplanwebsites** [comment]
Anyone managed to achieve this?

**Comment by oliverdunk** [comment]
There are a couple of options here:

- Check when needed / poll the [`chrome.runtime.getContexts`](https://developer.chrome.com/docs/extensions/reference/api/runtime#method-getContexts) method
- Open a message port with `chrome.runtime.connect` in your content script, and accept the connection in your side panel. Listen for the disconnect event.

We are open to adding an `onClose` event in the future, but we don't have that today.

**Comment by iplanwebsites** [comment]
Thanks @oliverdunk! Wasn't aware of `chrome.runtime.getContexts`.
I found disconnect event to be unreliable since the SW tend to sleep.
An `onClose` event would be great as polling and keeping workers alive just add more code & load.

**Comment by iplanwebsites** [comment]
Did some more experiments with , `chrome.runtime.getContexts` but there seem to be a limitation.
There is no `windowId` attached to `SidePanel`s, so we can't tell which window has the side panel open.

This is for a basic use case: hiding the _open panel_ button injected on the page when the panel is open.
Is there another way to assess which active panels belong to which windows/tabs?


<img width="287" alt="image" src="https://github.com/GoogleChrome/chrome-extensions-samples/assets/787729/7e726f74-0750-4131-ac63-4509eee80697">

**Comment by hskstu** [comment]
> There are a couple of options here:
> 
> * Check when needed / poll the [`chrome.runtime.getContexts`](https://developer.chrome.com/docs/extensions/reference/api/runtime#method-getContexts) method
> * Open a message port with `chrome.runtime.connect` in your content script, and accept the connection in your side panel. Listen for the disconnect event.
> 
> We are open to adding an `onClose` event in the future, but we don't have that today.

Hey @oliverdunk, adding some kind of event like `onClose` or `chrome.runTime.onContextsChange` or something to be able to hook into open/close events of the side panel would be super helpful to my team.

We're currently using `getContexts` where we can but to get everything we want, we'd have to poll.  If we switched to a connection, I think we'd have to send keepalive messages.  In either case the service worker doesn't get to sleep, which we'd like to allow it to do.

So mark me down as a +1 for that feature in the API, please 😄. Thank you!

**Comment by bashimr** [comment]
An `onClose` event would be super helpful. `chrome.runtime.connect` hack is a bad experience if there are multiple side panel paths that are loaded dynamically. You have to add `chrome.runtime.connect` on each one of the side panel pages as the user can close the side panel from any one of them. This hack works ok for a single page side panel but the problem is that the event also gets fired when the transition is happening from one side panel path to another. In multiple paths scenario, the side panel is not really closed, it is just switching from one path to another.

**Comment by Amitesh** [comment]
+1 for `onClose` event.

**Comment by adam-s** [comment]
The real question is whether the JavaScript context in the side panel is running.

(I haven't tested this in production so it might not work. Please let me know.)

```
    // Inside Side Panel
    document.addEventListener('visibilitychange', () => {
      // Create a listener that will check if the Javascript context running
      chrome.runtime.onMessage.addListener((message, _, sendResponse) => {
        if (
          message.type ===
          `sidePanelVisibilityChangeTest:${this.windowId}` // Listen for the background service worker to check if Javascript is running
        ) {
          setTimeout(() => { 
            sendResponse(); // STEP 4: If Javascript is running send a response
          }, 0);
          return true; // Wait for next event loop
        }
        return false;
      });
      // STEP 1: send a message. I track the windowId however any generated id will work.
      chrome.runtime.sendMessage({
        type: SIDE_PANEL_VISIBILITY_CHANGE,
        windowId: this.windowId,
      });
    });
```

```
       // Inside background service worker
       switch (message.type) {
          // STEP 2: Listen for the visibility change event
          case 'sidePanelVisibilityChange': {
            const { windowId } = message; // get the id from the message
            chrome.runtime
              .sendMessage({
                type: `sidePanelVisibilityChangeTest:${windowId}`, // STEP 3: Send a message including the id
              })
              .then(() => { // STEP 5a: If JavaScript is running
                this.settingsService.setSidePanelStatus(true, windowId);
              })
              .catch(() => { // STEP 5b: If JavaScript is not running, an error will be thrown.
                this.settingsService.setSidePanelStatus(false, windowId);
              });
            return false;
          }
```

**Comment by saqlain1020** [comment]
I found a brilliant workaround which works 100% of the time and not that much complex,

```
//content-script-ui

    onMessage("sidepanelClosed", () => {
      console.log("sidepanel closed");
    });
    onMessage("sidepanelOpened", () => {
      console.log("sidepanel opened");
    });
```

```
sidepanel.tsx

const sendSidepanelClosed = async () => {
  const { id } = await browser.windows.getCurrent();
  const tabs = await browser.tabs.query({ windowId: id });
  tabs.forEach((tab) => {
    sendMessage("sidepanelClosed", undefined, tab.id);
  });
};

const sendSidepanelOpened = async () => {
  const { id } = await browser.windows.getCurrent();
  const tabs = await browser.tabs.query({ windowId: id });
  tabs.forEach((tab) => {
    sendMessage("sidepanelOpened", undefined, tab.id);
  });
};

 useEffect(() => {
    sendSidepanelOpened();
    document.addEventListener("visibilitychange", sendSidepanelClosed);
    return () => {
      document.removeEventListener("visibilitychange", sendSidepanelClosed);
    };
  }, []);
```

I am using WXT and @webext-core/messaging

**Comment by tolotrasamuel** [comment]
> I found a brilliant workaround which works 100% of the time and not that much complex,
> 
> ```
> //content-script-ui
> 
>     onMessage("sidepanelClosed", () => {
>       console.log("sidepanel closed");
>     });
>     onMessage("sidepanelOpened", () => {
>       console.log("sidepanel opened");
>     });
> ```
> 
> ```
> sidepanel.tsx
> 
> const sendSidepanelClosed = async () => {
>   const { id } = await browser.windows.getCurrent();
>   const tabs = await browser.tabs.query({ windowId: id });
>   tabs.forEach((tab) => {
>     sendMessage("sidepanelClosed", undefined, tab.id);
>   });
> };
> 
> const sendSidepanelOpened = async () => {
>   const { id } = await browser.windows.getCurrent();
>   const tabs = await browser.tabs.query({ windowId: id });
>   tabs.forEach((tab) => {
>     sendMessage("sidepanelOpened", undefined, tab.id);
>   });
> };
> 
>  useEffect(() => {
>     sendSidepanelOpened();
>     document.addEventListener("visibilitychange", sendSidepanelClosed);
>     return () => {
>       document.removeEventListener("visibilitychange", sendSidepanelClosed);
>     };
>   }, []);
> ```
> 
> I am using WXT and @webext-core/messaging

no really 100%. This does not fire if the window is closes before the event is reaches the sendMessage

**Comment by iamqiz** [comment]
I need onOpen/onClose event and getStatus method ! please add it, thanks!

**Comment by oliverdunk** [comment]
> I need onOpen/onClose event and getStatus method ! please add it, thanks!

We're actively working on onOpened and onClosed events, and they should be landing soon. We'll share more details on https://developer.chrome.com/docs/extensions/whats-new when these are available.

**Comment by iamqiz** [comment]
> We're actively working on onOpened and onClosed events,

@oliverdunk good job! thanks!

by the way, I know you yesterday in below post when I search google about tab.lastAccessed :
Tab.lastAccessed Not Reliably Updating
https://groups.google.com/a/chromium.org/g/chromium-extensions/c/rRMwMTAAB2I
it will be good if tab has a lastFocus attribute so that I can get recent tabs that  user access , do you have plan to add it? 😃

**Comment by oliverdunk** [comment]
> > We're actively working on onOpened and onClosed events,
> 
> [@oliverdunk](https://github.com/oliverdunk) good job! thanks!
> 
> by the way, I know you yesterday in below post when I search google about tab.lastAccessed : Tab.lastAccessed Not Reliably Updating https://groups.google.com/a/chromium.org/g/chromium-extensions/c/rRMwMTAAB2I it will be good if tab has a lastFocus attribute so that I can get recent tabs that user access , do you have plan to add it? 😃

We don't have any plans for this at the moment. If you have ideas, https://groups.google.com/a/chromium.org/g/chromium-extensions is a better forum for that, as this is just the issue tracker for samples and we can't properly handle feature requests here.
